CREATE DATABASE IF NOT EXISTS COMP2800;
        use COMP2800;
        CREATE TABLE IF NOT EXISTS BBY_8_user (
            ID int NOT NULL AUTO_INCREMENT,
            firstName varchar(30),
            lastName varchar(30),
            email varchar(30),
            password varchar(30),
            role char,
            userName varchar(30),
            age int,
            personality varchar(30),
            filesrc varchar (100),
            PRIMARY KEY (ID)
        );
        use COMP2800;
        CREATE TABLE IF NOT EXISTS BBY_8_survey (
            userID int NOT NULL,
            dateOfSurvey DATE,
            survey varchar(30),
            PRIMARY KEY (userID, dateOfSurvey),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID)
        );
        CREATE TABLE IF NOT EXISTS BBY_8_album (
            ID int NOT NULL AUTO_INCREMENT,
            title varchar(30), 
            artist varchar(30),
            genre varchar(30),
            dateofRelease DATE,
            filesrc varchar (100),
            PRIMARY KEY (ID)
        );
        CREATE TABLE IF NOT EXISTS BBY_8_song (
            ID int NOT NULL AUTO_INCREMENT,
            title varchar(50),
            artist varchar(80),
            personality varchar(4),
            mood varchar(30), 
            album varchar(80),
            youtubeLink varchar(70),
            spotifyLink varchar(80),
            filesrc varchar (100),            
            PRIMARY KEY (ID)
        );
        CREATE TABLE IF NOT EXISTS BBY_8_library (
            userID int NOT NULL,
            songID int NOT NULL,
            PRIMARY KEY (userID, songID),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID),
            FOREIGN KEY (songID) REFERENCES BBY_8_song(ID)
        );
        CREATE TABLE IF NOT EXISTS BBY_8_review (
            userID int NOT NULL,
            songID int NOT NULL,
            dateOfReview DATE,
            review varchar(150),
            PRIMARY KEY (userID, songID, dateOfReview),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID),
            FOREIGN KEY (songID) REFERENCES BBY_8_song(ID)
        );
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("John", "Smith", "JS@test.ca", "1234", 'A', "JohnCena420", "69", "INFJ", "default");
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("Jason", "Turner", "jasonTurn@tec.ca", "4312", 'R', "JasonSparrow", "34", "ENFJ", "default");
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("Amy", "Santiago", "AMS@brook.ca", "JQRIBVQIX23", 'R', "TheTerminator", "30", "INTP", "default");
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("Diego", "Cuenca Espino", "dce@my.bcit.ca", "notabc123", 'A', "DCE", "21", "INTP", "default");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Depression Cherry", "Beach House", "Dream Pop", "2015-08-28", "beach-house-depression-cherry.png");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Thank Your Lucky Stars", "Beach House", "Dream Pop", "2015-10-16", "beach-house-thank-your.png");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Fuzzybrain", "Dayglow", "Indie Pop", "2018-09-28", "hot-rod-dayglow.jpg");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Appetite for Destruction", "Guns N' Roses", "Hard Rock", "1987-07-21", "guns-n-roses-appetite.jpg");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("True", "Avicii", "EDM", "2013-09-13", "avicii-true.jpg");
INSERT INTO BBY_8_song (title, artist, personality, mood, album, youtubeLink, spotifyLink, filesrc)
    VALUES ("Bach: Cello Suite No.! in G Major", "Yo-Yo Ma", "ISTJ", "TBD", "Six Suites for Unaccompanied Cello", "https://youtu.be/pAgnJDJN4VA?list=PLv5D2n4QoJbrgC3LQo9PAzTZccsgDANBh", "https://open.spotify.com/track/7sjuI9Y9rsrWOJUNVzqOK7?autoplay=true", "bach-cello-yo-yo-ma.jpg");
INSERT INTO BBY_8_song (title, artist, personality, mood, album, youtubeLink, spotifyLink, filesrc)
    VALUES ("Nocturne op.9 No.2", "Chopin", "ISTJ", "TBD", "Chopin: Nocturnes", "https://www.youtube.com/watch?v=9E6b3swbnWg", "https://open.spotify.com/track/61dYvvfIRtIDFuqZypPAta", "nocturne-chopin.jpg");
INSERT INTO BBY_8_song (title, artist, personality, mood, album, youtubeLink, spotifyLink, filesrc)
    VALUES
    ('Space Song','Beach House','ENFJ','Stressed','Depression Cherry','https://www.youtube.com/watch?v=RBtlPT23PTM','https://open.spotify.com/track/7H0ya83CMmgFcOhw0UB6ow?si=58caf26bc2d64dc5','beach-house-depression-cherry.png'),
    ('Myth','Beach House','ENFJ','Stressed','Bloom','https://www.youtube.com/watch?v=FuvWc3ToDHg','https://open.spotify.com/track/2NfxtzCIrpCmJX5Z2KMdD5?si=6fd60bbfba264f3a','beach-house-myth.jpg'),
    ('Pretty Girl','Clairo','ENFJ','Stressed','Pretty Girl','https://www.youtube.com/watch?v=mngtcfcaVrI','https://open.spotify.com/track/0KyAGiNGUytG5JLxJu4F6l?si=d9c07d6ed1724237','pretty-girl-clairo.jpg'),
    ('Hot Rod','Dayglow','ENFJ','Stressed','Fuzzybrain','https://www.youtube.com/watch?v=RUih0WRFI-g','https://open.spotify.com/track/12j3KX5TkcAswLUUPMTNqA?si=144727caaba74c1e','hot-rod-dayglow.jpg'),
    ('Can I Call You Tonight','Dayglow','ENFJ','Stressed','Fuzzybrain','https://www.youtube.com/watch?v=hh1WeQxfCX0','https://open.spotify.com/track/5Ti99QiUdIwe0xG4gS22FL?si=4bf1bca88eb64f51','can-i-call-you-tonight-dayglow.jpg'),
    ('MotionSickness','Phoebe Bridgers','ENFJ','Stressed','Stranger in the Alps','https://www.youtube.com/watch?v=9sfYpolGCu8','https://open.spotify.com/track/6LxcPUqx6noURdA5qc4BAT?si=0d72e75851ae461a','motion-sickness-phoebe.jpg'),
    ('Heather','Conan Gray','ENFJ','Stressed','Kid Krow','https://www.youtube.com/watch?v=24u3NoPvgMw','https://open.spotify.com/track/4xqrdfXkTW4T0RauPLv3WA?si=6c56af70621c458f','heather-conan-gray.jpg'),
    ('Sunflower','Rex Orange County','ENFJ','Stressed','Sunflower','https://www.youtube.com/watch?v=V0X-SWiDr1g','https://open.spotify.com/track/4EpZ4eYuZOwPSSwyqpdHnJ?si=979e63a8fc0a4550','sunflower-rex-orange.jpg'),
    ('Pluto Projector','Rex Orange County','ENFJ','Stressed','Pony','https://www.youtube.com/watch?v=Pi9J4epTWGM','https://open.spotify.com/track/4EWBhKf1fOFnyMtUzACXEc?si=aae4be632a12479f','pluto-projector-rex-orange.jpg'),
    ('Cigarette Daydreams','Cage The Elephant','ENFJ','Stressed','Melophobia','https://www.youtube.com/watch?v=D9qhL-RckVA','https://open.spotify.com/track/2tznHmp70DxMyr2XhWLOW0?si=1d53f49fa78e487c','cigarette-daydreams-cage.jpg'),
    ('Dark Red','Steve Lacy','ENFJ','Stressed','Dark Red','https://www.youtube.com/watch?v=xRzbLQ_WKPs','https://open.spotify.com/track/37y7iDayfwm3WXn5BiAoRk?si=e7a0e11db3ac4fe1','dark-red-steve-lacy.jpg'),
    ('Peach Pit','Peach Pit','ENFJ','Neutral','Sweet FA','https://www.youtube.com/watch?v=p4y4eT1cJ54','https://open.spotify.com/track/0ZK8TGOsngrstVPsnrHbK1?si=07808b7c2ee442dc','peach-pit.jpg'),
    ('BESTINTEREST','Tyler, The Creator','ENFJ','Happy','BEST INTEREST','https://www.youtube.com/watch?v=NkMTKGM-efw','https://open.spotify.com/track/3jHdKaLCkuNEkWcLVmQPCX?si=5fa9ef9882984a74','best-interest-tyler.jpg'),
    ('3Nights','Dominic FIke','ENFJ','Stressed','Don''t Forget About Me, Demos','https://www.youtube.com/watch?v=OWKzRngush4','https://open.spotify.com/track/1tNJrcVe6gwLEiZCtprs1u?si=3e8373d529324b06','3-nights-dominic.jpg'),
    ('Homage','Mild High Club','ENFJ','Neutral','Skiptracing','https://www.youtube.com/watch?v=Yv3OFuzYWDU','https://open.spotify.com/track/7pegxVesMmE2qK0o58xoFG?si=6aae0fddcb114cd3','mild-high-club-homage.jpg'),
    ('Boredom','Tyler, The Creator','ENFJ','Stressed','FlowerBoy','https://www.youtube.com/watch?v=jxlBOBOZHqI','https://open.spotify.com/track/5WNYg3usc6H8N3MBEp4zVk?si=6a9dd4e7af7f4190','boredom-tyler.jpg'),
    ('No Surprises','Radiohead','INTP','Neutral','OK Computer','https://www.youtube.com/watch?v=u5CVsCnxyXg','https://open.spotify.com/track/10nyNJ6zNy2YVYLrcwLccB?si=42d4fe6846194e36','no-surprises-radiohead.jpg'),
    ('Weird Fishes/Arpeggi','Radiohead','INTP','Neutral','In Rainbows','https://www.youtube.com/watch?v=V_Ydoe4Q-Gg','https://open.spotify.com/track/4wajJ1o7jWIg62YqpkHC7S?si=74af5808f9c74dca','weird-fishes-radiohead.jpg'),
    ('I Miss You','blink-182','INTP','Neutral','Blink182','https://www.youtube.com/watch?v=s1tAYmMjLdY','https://open.spotify.com/track/5glvnkBJ4sLrObTyprSsPg?si=d0816f8995d74e9c','i-miss-you-blind182.jpg'),
    ('Island In The Sun','Weezer','INTP','Neutral','Smallville:The Talon Mix','https://www.youtube.com/watch?v=erG5rgNYSdk','https://open.spotify.com/track/1IRZwD3r9VOehOR8rGeV3Y?si=e8c6b25289224c93','island-in-the-sun-weezer.jpg'),
    ('The Man Who Sold The World','Nirvana','INTP','Stressed','MTV Unplugged In NewYork','https://www.youtube.com/watch?v=fregObNcHC8','https://open.spotify.com/track/48psxWnIVYCPUZJKiuDiEf?si=da0af95eaf3846cd','the-man-who-sold-the-world-nirvana.jpg'),
    ('Exit Music For A Film','Radiohead','INTP','Neutral','OK Computer','https://www.youtube.com/watch?v=Bf01riuiJWA','https://open.spotify.com/track/0z1o5L7HJx562xZSATcIpY?si=44a44768b08345ec','exit-music-for-a-film-radiohead.jpg'),
    ('Sunday Morning','The Velvet Underground, Nico','INTP','Happy','The Velvet Underground and Nico','https://www.youtube.com/watch?v=Xhbyj8pqUao','https://open.spotify.com/track/11607FzqoipskTsXrwEHnJ?si=7ec6b48ceb034b91','sunday-morning-the-velvet-underground.jpg'),
    ('Femme Fatale','The Velvet Underground, Nico','INTP','Happy','The Velvet Underground and Nico','https://www.youtube.com/watch?v=3wNNG49Jz48','https://open.spotify.com/track/3PG7BAJG9WkmNOJOlc4uAo?si=58bffadfcf0c453b','femme-fatale-the-velvet-underground.jpg'),
    ('She Brings The Rain','CAN','INTP','Stressed','Soundtracks','https://www.youtube.com/watch?v=3wNNG49Jz48','https://open.spotify.com/track/798UQDI0kkPc562NvOZ163?si=9c03778c846c4214','she-brings-the-rain-can.jpg'),
    ('Moonshake','CAN','INTP','Neutral','Future Days','https://www.youtube.com/watch?v=JAdNjKAAj_o','https://open.spotify.com/track/6ACXIPu0jhLDriV5sjrWtb?si=34dd75ecf48e4358','moon-shake-can.jpg'),
    ('Singapore','Tom Waits','INTP','Happy','Rain Dogs','https://www.youtube.com/watch?v=DfvASyLcKs4','https://open.spotify.com/track/1NmUM1cIycWhgSz1qKmCXh?si=900867e598ff4cc1','singapore-tom-waits.jpg'),
    ('Downtown Train','Tom Waits','INTP','Stressed','Rain Dogs','https://www.youtube.com/watch?v=qWDJIwqCXi4','https://open.spotify.com/track/3fPqUl4lPDUQmY0T7dKUv2?si=5d29c4d0c6ae475b','singapore-tom-waits.jpg'),
    ('Paper Hats','This Heat','INTP','angry','Deceit','https://www.youtube.com/watch?v=DkiK_YHxv0I','https://open.spotify.com/track/0XqKAig27dZT9AXcup5Zj0?si=98a19e96e908448a','paper-hats-this-heat.jpg'),
    ('Silence','Portishead','INTP','Neutral','Third','https://www.youtube.com/watch?v=0Y35MdpqMRk','https://open.spotify.com/track/6CLLkUajKRN9LS9PeK3OZF?si=923818b57caf46c9','silence-portishead.jpg'),
    ('The Rip','Portishead','INTP','Stressed','Third','https://www.youtube.com/watch?v=kBOaLjtR4mw','https://open.spotify.com/track/5KX2DSPC6aCA0pdDidTmBC?si=f5f128a241934129','the-rip-portishead.jpg'),
    ('Hey','Pixies','INTP','Neutral','Doolittle','https://www.youtube.com/watch?v=tVCUAXOBF7w','https://open.spotify.com/track/0p5eZCY0R7uNCZS1YDtIYI?si=79f31991ea3a46e7','hey-pixies.jpg'),
    ('AllTheSmallThings','blink-182','ENTP','Neutral','Enema Of The State','https://www.youtube.com/watch?v=9Ht5RZpzPqw','https://open.spotify.com/track/7yCPwWs66K8Ba5lFuU2bcx?si=59940ff992fd4563','default-song.png'),
    ('Teenagers','My Chemical Romance','ENTP','Happy','The Black Parade','https://www.youtube.com/watch?v=k6EQAOmJrbw','https://open.spotify.com/track/7j31rVgGX9Q2blT92VBEA0?si=84bb8bc179a94ef0','default-song.png'),
    ('WelcometotheBlackParade','My Chemical Romance','ENTP','Stressed','The Black Parade','https://www.youtube.com/watch?v=RRKJiM9Njr8','https://open.spotify.com/track/5wQnmLuC1W7ATsArWACrgW?si=af18880e77bc455b','default-song.png'),
    ('HashPipe','Weezer','ENTP','angry','Weezer (GreenAlbum)','https://www.youtube.com/watch?v=_9BGLtqqkVI','https://open.spotify.com/track/29xKs5BAHlmlX1u4gzQAbJ?si=d16596cf590246c7','default-song.png'),
    ('BasketCase','Green Day','ENTP','Happy','Dookie','https://www.youtube.com/watch?v=NUTGr5t3MoY','https://open.spotify.com/track/6L89mwZXSOwYl76YXfX13s?si=2bc2869201874df2','default-song.png'),
    ('Sugar,We''reGoinDown','Fall Out Boy','ENTP','Neutral','From Under The Cork Tree','https://www.youtube.com/watch?v=uhG-vLZrb-g','https://open.spotify.com/track/2TfSHkHiFO4gRztVIkggkE?si=34936db55c1f4aae','default-song.png'),
    ('Stacy''sMom','Fountains Of Wayne','ENTP','Happy','Welcome Interstate Managers','https://www.youtube.com/watch?v=dZLfasMPOU4','https://open.spotify.com/track/27L8sESb3KR79asDUBu8nW?si=e0ffa103d8a74405','default-song.png'),
    ('TimeBomb','Rancid','ENTP','Happy','...And Out Come The Wolves','https://www.youtube.com/watch?v=DhKHAopx7D0','https://open.spotify.com/track/7goMqXhydyyhmWdPxLTm7E?si=002900dd2c2c4a45','default-song.png'),
    ('IWasWrong','Social Distortion','ENTP','Neutral','White Light White Heat White Trash','https://www.youtube.com/watch?v=aXAU4MmMIMo','https://open.spotify.com/track/1Lpmme6uCsPJIdcbR5aePx?si=e72617fbd58d4aab','default-song.png'),
    ('LondonCalling','The Clash','ENTP','Angry','London Calling','https://www.youtube.com/watch?v=EfK-WX2pa8c','https://open.spotify.com/track/5jzma6gCzYtKB1DbEwFZKH?si=e440899a3e9d4f7d','default-song.png'),
    ('TraininVain','The Clash','ENTP','Happy','London Calling','https://www.youtube.com/watch?v=zqZSONJYNGI','https://open.spotify.com/track/6ITuEsxEy2qPhqMowdDAeI?si=bbb4279c71e04757','default-song.png'),
    ('CaliforniaUberAlles','Dead Kennedys','ENTP','Angry','Give Me Convenience or Give Me Death','https://www.youtube.com/watch?v=jrWflCJPM4w','https://open.spotify.com/track/5szJ8SMwQVEvvdk65w6M6g?si=e6661aacea224bb2','default-song.png'),
    ('HolidayinCambodia','Dead Kennedys','ENTP','Angry','Fresh Fruit For Rotting Vegetables','https://www.youtube.com/watch?v=Qr6NOsluHYg','https://open.spotify.com/track/6ZR7gzHIvcj4qvo5q4kqXN?si=5312ed4a4a1045ea','default-song.png'),
    ('NaziPunksFuckOff','Dead Kennedys','ENTP','Angry','Plastic Surgery Disasters','https://www.youtube.com/watch?v=iyc62g7YQM0','https://open.spotify.com/track/2LF13LC1wG5XqZ2js2yC9O?si=5a8b0208f9e24010','default-song.png'),
    ('TooDrunktoFuck','Dead Kennedys','ENTP','Angry','Fresh Fruit For Rotting Vegetables','https://www.youtube.com/watch?v=4ncqvLktdT8','https://open.spotify.com/track/5VTT6Qxr5938lOmStMJXhB?si=9e4ce66ccb934163','default-song.png'),
    ('YouthofAmerica','Wipers','ENTP','Angry','Youth of America','https://www.youtube.com/watch?v=YaUzYISKKAI','https://open.spotify.com/track/2Dj59k8Rar55hTbzwCt2bK?si=c23287f4c8ac4e17','default-song.png'),
    ('WhenIt''sOver','Wipers','ENTP','Neutral','Youth of America','https://www.youtube.com/watch?v=tUm_FeB0KlQ','https://open.spotify.com/track/59RkLuqY3LSqK3rJGds6cP?si=654588c8490942a7','default-song.png'),
    ('IGottaFeeling','Black Eyed Peas','ISFP','Happy','The E.N.D','https://www.youtube.com/watch?v=uSD4vsh1zDA','https://open.spotify.com/track/4vp2J1l5RD4gMZwGFLfRAu?si=994df531df61441c','default-song.png'),
    ('PartyRockAnthem','LMFAO','ISFP','Happy','Sorry For Party Rocking','https://www.youtube.com/watch?v=KQ6zr6kCPj8','https://open.spotify.com/track/7mitXLIMCflkhZiD34uEQI?si=21e980f469394ceb','default-song.png'),
    ('LikeAG6','Far East Movement','ISFP','Neutral','Dirty Bass','https://www.youtube.com/watch?v=w4s6H4ku6ZY','https://open.spotify.com/track/2s5YN9O8Qv25BjQobPHWVZ?si=27c9ed687c3b4880','default-song.png'),
    ('HeadandHeart','Joel Corry','ISFP','Happy','Heart and Heart','https://www.youtube.com/watch?v=CRuOOxF-ENQ','https://open.spotify.com/track/6cx06DFPPHchuUAcTxznu9?si=7d45847e0e43457f','default-song.png'),
    ('CrazyInLove','Beyonce, Jay-Z','ISFP','Happy','Dangerously In Love','https://www.youtube.com/watch?v=ViwtNLUqkMY','https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr?si=8163e16b0b4a4b19','default-song.png'),
    ('LastFridayNight','Kay Perry','ISFP','Happy','Teenage Dream','https://www.youtube.com/watch?v=KlyXNRrsk4A','https://open.spotify.com/track/455AfCsOhhLPRc68sE01D8?si=10715267fb3b44a4','default-song.png'),
    ('JustDance','Lady Gaga','ISFP','Happy','The Fame','https://www.youtube.com/watch?v=gwrZEmYEotQ','https://open.spotify.com/track/1dzQoRqT5ucxXVaAhTcT0J?si=b933198442704c9a','default-song.png'),
    ('ScreamandShout','will.i.am, Britney Spears','ISFP','Stressed','#willpower','https://www.youtube.com/watch?v=kYtGl1dX5qI','https://open.spotify.com/track/2iJuuzV8P9Yz0VSurttIV5?si=1581bf01fc544c8e','default-song.png'),
    ('HeyYa','Outkast','ISFP','Happy','Speakerboxxx/The Love Below','https://www.youtube.com/watch?v=PWgvGjAhvIw','https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM?si=5f816175d3644942','default-song.png'),
    ('WaitingForLove','Avicii','ISFP','Neutral','Stories','https://www.youtube.com/watch?v=cHHLHGNpCSA','https://open.spotify.com/track/2P4OICZRVAQcYAV2JReRfj?si=765896efd7f54dec','default-song.png'),
    ('Starships','Nicki Minaj','ISFP','Happy','Pink Friday...Roman Reloaded','https://www.youtube.com/watch?v=SeIJmciN8mo','https://open.spotify.com/track/1oHNvJVbFkexQc0BpQp7Y4?si=53c70b6c44304eb7','default-song.png'),
    ('WeFoundLove','Rihanna, Calvin Harris','ISFP','Stressed','Talk That Talk','https://www.youtube.com/watch?v=tg00YEETFzg','https://open.spotify.com/track/6qn9YLKt13AGvpq9jfO8py?si=cb9c124994724e9d','default-song.png'),
    ('Timber','Pitbull, Kesha','ISFP','Happy','Global Warming:Meltdown','https://www.youtube.com/watch?v=hHUbLv4ThOo','https://open.spotify.com/track/3cHyrEgdyYRjgJKSOiOtcS?si=5479e322ae034ef6','default-song.png'),
    ('Whistle','Flo Rida','ISFP','Happy','Wild Ones','https://www.youtube.com/watch?v=cSnkWzZ7ZAA','https://open.spotify.com/track/3bC1ahPIYt1btJzSSEyyrF?si=dd9944c30bfb44dd','default-song.png'),
    ('Don''tStopTheMusic','Rihanna','ISFP','Happy','Good Girl Gone Bad','https://www.youtube.com/watch?v=yd8jh9QYfEs','https://open.spotify.com/track/0ByMNEPAPpOR5H69DVrTNy?si=e5a5bb681ef9451a','default-song.png'),
    ('Toxic','Brittney Spears','ISFP','Happy','In The Zone','https://www.youtube.com/watch?v=LOZuxwVk7TU','https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak?si=157cf35f82a34eec','default-song.png'),
    ('PartyInTheUSA','Miley Cyrus','ISFP','Happy','The Time Of Our Lives','https://www.youtube.com/watch?v=M11SvDtPBhA','https://open.spotify.com/track/3E7dfMvvCLUddWissuqMwr?si=152842e59a7e497f','default-song.png'),
    ('UptownFunk','Bruno Mars','ISFP','Happy','Uptown Special','https://www.youtube.com/watch?v=OPf0YbXqDm0','https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS?si=3a4d741c064e4f9e','default-song.png'),
    ('SymptomoftheUniverse','Black Sabbath','ENTJ','Angry','Sabotage','https://www.youtube.com/watch?v=4g_Yk6eKlwk','https://open.spotify.com/track/7lwCPihf6s0609Q5uBjXrF?si=a1693ff693bc4f4c','default-song.png'),
    ('TheTrooper','Iron Maiden','ENTJ','Angry','Piece of Mind','https://www.youtube.com/watch?v=X4bgXH3sJ2Q','https://open.spotify.com/track/4OROzZUy6gOWN4UGQVaZMF?si=17fac4af9a8d470a','default-song.png'),
    ('Paranoid','Black Sabbath','ENTJ','Angry','Paranoid','https://www.youtube.com/watch?v=0qanF-91aJo','https://open.spotify.com/track/3q9G9SvgdfE1fxlvoDIb20?si=132bbe441a744227','default-song.png'),
    ('CrazyTrain','Ozzy Osbourne','ENTJ','Angry','Blizzard of Ozz','https://www.youtube.com/watch?v=tMDFv5m18Pw','https://open.spotify.com/track/2b9lp5A6CqSzwOrBfAFhof?si=9b9ac96f21d24be8','default-song.png'),
    ('MasterofPuppets','Metallica','ENTJ','Angry','Master Of Puppets','https://www.youtube.com/watch?v=0obBdrfUMzU','https://open.spotify.com/track/6NwbeybX6TDtXlpXvnUOZC?si=348b3cbb001d42e2','default-song.png'),
    ('HeavenandHell','Black Sabbath','ENTJ','Stressed','Heaven and Hell','https://www.youtube.com/watch?v=5FRA7UXlGu8','https://open.spotify.com/track/6LtNEH08J18r4HLs4HzvqW?si=a86a1db8bbf845d9','default-song.png'),
    ('WelcomeToTheJungle','Guns N'' Roses','ENTJ','Happy','Appetite For Destruction','https://www.youtube.com/watch?v=o1tj2zJ2Wvg','https://open.spotify.com/track/0oWHLtxWeMJhmwxtrxhNK0?si=c8cf1a94f62b4573','default-song.png'),
    ('SeekandDestroy','Metallica','ENTJ','Angry','Kill ''Em All','https://www.youtube.com/watch?v=Wm58sGEdgAw','https://open.spotify.com/track/1LDAh7QQnWvp3GJ9QDa1Pj?si=9ec8451a4ef74938','default-song.png'),
    ('Runnin''WithTheDevil','Van Halen','ENTJ','Angry','Van Halen','https://www.youtube.com/watch?v=enL_lzVyNdM','https://open.spotify.com/track/3gLlcZQMvpwgtV9THHXrGp?si=7c34d9292a2041e6','default-song.png'),
    ('BackattheMoon','Ozzy Osbourne','ENTJ','Angry','Bark At The Moon','https://www.youtube.com/watch?v=F89-MOy7Xfg','https://open.spotify.com/track/2E7W1X4maFFcjHrVrFA7Vs?si=b2f9cadd0e0d482f','default-song.png'),
    ('Ghost','Nightmares','ENTJ','Angry','After Death','https://www.youtube.com/watch?v=4tDwAeCkpho','https://open.spotify.com/track/7kLzH5kMAxvWuqYjGoUX8t?si=179dbb2ebe7b4288','default-song.png'),
    ('IntheEnd','Linkin Park','ENTJ','Stressed','Hybrid Theory','https://www.youtube.com/watch?v=eVTXPUF4Oz4','https://open.spotify.com/track/3tSmXSxaAnU1EPGKa6NytH?si=ae5b65be7b8b41d5','default-song.png'),
    ('Hangar18','Megadeth','ENTJ','Angry','Rust In Peace','https://www.youtube.com/watch?v=x5A9Aa-WU5E','https://open.spotify.com/track/6b6uLZsoGhObYexIxnRbIb?si=801b1d6630cc47c9','default-song.png'),
    ('God''sCountry','Blake Shelton','ISFJ','Stressed','Fully Loaded:God''s Country','https://www.youtube.com/watch?v=ZEWGyyLiqY4','https://open.spotify.com/track/4TCeFZNjGNQIpCuZmJkkE2?si=d37d42bfb61e45c3','default-song.png'),
    ('BigIron','Marty Robbins','ISFJ','Stressed','Gunfighter Ballads And Trail Songs','https://www.youtube.com/watch?v=zzICMIu5zFY','https://open.spotify.com/track/0AQquaENerGps8BQmbPw14?si=abd7ae1839634f51','default-song.png'),
    ('Jolene','Dolly Parton','ISFJ','Stressed','Jolene','https://www.youtube.com/watch?v=Ixrje2rXLMA','https://open.spotify.com/track/2SpEHTbUuebeLkgs9QB7Ue?si=71aed85fa46841ff','default-song.png'),
    ('DaddySangBass','Johnny Cash','ISFJ','Happy','The Essential Johnny Cash','https://www.youtube.com/watch?v=x_geYBnMNG0','https://open.spotify.com/track/15TITugVC8RrpLctHXOqT8?si=8afbd45c6ff84e1d','default-song.png'),
    ('AchyBreakyHeart','Billy Ray Cyrus','ISFJ','Happy','Some Gave All','https://www.youtube.com/watch?v=byQIPdHMpjc','https://open.spotify.com/track/2EoIt9vdgFRNW03u5IvFsQ?si=8bd89b6039e54b2c','default-song.png'),
    ('ChickenFried','Zac Brown Band','ISFJ','Happy','The Foundation','https://www.youtube.com/watch?v=e4ujS1er1r0','https://open.spotify.com/track/3eBnEo9WL34ulBCZlLpUQO?si=e97c57e97111441e','default-song.png'),
    ('GoodBeer','Seaforth, Jordan Davis','ISFJ','Happy','Good Beer','https://www.youtube.com/watch?v=JzGef7-WvTw','https://open.spotify.com/track/55M9eKCXJFCpid6WBVyEct?si=e3319c2b21c0480f','default-song.png'),
    ('ILikeTheSoundOfThat','Rascal Flatts','ISFJ','Stressed','Rewind','https://www.youtube.com/watch?v=TIwKZLcQM0E','https://open.spotify.com/track/5S5rw0WLVCAux5B5bWCehK?si=fc249ee476d349f5','default-song.png'),
    ('AGuywithaGirl','Blake Shelton','ISFJ','Happy','If I''m Honest','https://www.youtube.com/watch?v=dnDYhIQ-YOI','https://open.spotify.com/track/5sjIhQzNljMVrDklI91ezp?si=daaa57ed07914fc3','default-song.png'),
    ('WhiskeyGlasses','Morgan Wallen','ISFJ','Stressed','If I Know Me','https://www.youtube.com/watch?v=FjBp30kjzTc','https://open.spotify.com/track/6foY66mWZN0pSRjZ408c00?si=d90963b5f2cf4bf4','default-song.png'),
    ('WagonWheel','Darius Rucker','ISFJ','Neutral','True Believers','https://www.youtube.com/watch?v=hvKyBcCDOB4','https://open.spotify.com/track/3xdjjKMcMOFgo1eQrfbogM?si=7835f2b0767b4139','default-song.png'),
    ('GoodGirl','Dustin Lynch','ISFJ','Neutral','Good Girl','https://www.youtube.com/watch?v=cPLctS4kqk8','https://open.spotify.com/track/5HnXcJJbNXQQ7tRlQ9VN1v?si=186fa8fc3d4f4c92','default-song.png'),
    ('BeerCan''tFix','Thomas Rhett, Jon Pardi','ISFJ','Stressed','Center Point Road','https://www.youtube.com/watch?v=rct9Zs_Yd-I','https://open.spotify.com/track/7idmHTAQQPUFqdjXkoooXD?si=1488b1280bc34dc5','default-song.png'),
    ('Drinkin''Beer.Talkin''God.Amen.','Chase Rice, Florida Georgia Line','ISFJ','Happy','Drinkin''Beer.Talkin''God.Amen.','https://www.youtube.com/watch?v=wpS2oX9ASLc','https://open.spotify.com/track/1UYfAU2bwgjaM5rIIPQleC?si=a9d6dfa824354d3f','default-song.png'),
    ('BeersAndSunshine','Darius Rucker','ISFJ','Happy','Beers And Sunshine','https://www.youtube.com/watch?v=s-vjdUg2bNk','https://open.spotify.com/track/36ISlLb12gKuCCVTYXC0gb?si=2cd5ccc760074f4a','default-song.png'),
    ('TennesseeWhiskey','Chris Stapleton','ISFJ','Stressed','Traveller','https://www.youtube.com/watch?v=4zAThXFOy2c','https://open.spotify.com/track/3fqwjXwUGN6vbzIwvyFMhx?si=f80aae66363d4946','default-song.png'),
    ('She''sCountry','Jason Aldean','ISFJ','Neutral','Wider Open','https://www.youtube.com/watch?v=ZsvR6XAl1os','https://open.spotify.com/track/0PspNrE4MSjr1JeB4OW0jn?si=abf3557380b648aa','default-song.png'),
    ('Knockin''Boots','Luke Bryan','ISFJ','Neutral','Born Here Live Here Die Here','https://www.youtube.com/watch?v=Ioz93bSi2uc','https://open.spotify.com/track/2opQESZb7JsRKCvWMBPeuv?si=09a29b7aff464b0e','default-song.png'),
    ('PurpleLamborghini','Skrillex, Rick Ross','INTJ','Angry','Purple Lamborghini','https://www.youtube.com/watch?v=ZkqyIoYAXV8','https://open.spotify.com/track/6JyuJFedEvPmdWQW0PkbGJ?si=adbe1a00804f4875','default-song.png'),
    ('WhereAreUNow','Jack U, Skrillex, Diplo, Justin Bieber','INTJ','Stressed','Skrillex and Diplo present Jack U','https://www.youtube.com/watch?v=nntGTK2Fhb0','https://open.spotify.com/track/66hayvUbTotekKU3H4ta1f?si=9346b3c5f6ae499d','default-song.png'),
    ('Daylight','Joji, Diplo','INTJ','Stressed','Daylight','https://www.youtube.com/watch?v=jOTqYGNaD6E','https://open.spotify.com/track/6Ed1q0X8oSKSm4IIhiQbYg?si=50932ad96bcc4c7b','default-song.png'),
    ('Harder,Better,Faster,Stronger','Daft Punk','INTJ','Neutral','Discovery','https://www.youtube.com/watch?v=gAjR4_CbPpQ','https://open.spotify.com/track/5W3cjX2J3tjhG8zb6u0qHn?si=9e91401d28314c68','default-song.png'),
    ('GetLucky','Daft Punk, Pharrell Williams, Nile Rodgers','INTJ','Happy','Random Acess Memories','https://www.youtube.com/watch?v=5NV6Rdv1a3I','https://open.spotify.com/track/69kOkLUCkxIZYexIgSG8rq?si=77e378230d9f458e','default-song.png'),
    ('WakeMeUp','Avicii','INTJ','Stressed','True','https://www.youtube.com/watch?v=IcrbM1l_BoI','https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2?si=5b10e86c98a24d0f','default-song.png'),
    ('WaitingForLove','Avicii','INTJ','Stressed','Stories','https://www.youtube.com/watch?v=cHHLHGNpCSA','https://open.spotify.com/track/2P4OICZRVAQcYAV2JReRfj?si=64b1228528f8405d','default-song.png'),
    ('TheMiddle','Zedd, Maren Morris, grey','INTJ','Stressed','The Middle','https://www.youtube.com/watch?v=Lj6Y6JCu-l4','https://open.spotify.com/track/09IStsImFySgyp0pIQdqAc?si=33c921f059314a8f','default-song.png'),
    ('Stay','Zedd, Alessia Cara','INTJ','Stressed','Stay','https://www.youtube.com/watch?v=h--P8HzYZ74','https://open.spotify.com/track/6uBhi9gBXWjanegOb2Phh0?si=e418a57fe6d6411d','default-song.png'),
    ('Happier','Marshmello, Bastille','INTJ','Stressed','Happier','https://www.youtube.com/watch?v=m7Bc3pLyij0','https://open.spotify.com/track/2dpaYNEQHiRxtZbfNsse99?si=2e7d09f91bda4757','default-song.png'),
    ('Memories','David Guetta, Kid Cudi','INTJ','Happy','Memories','https://www.youtube.com/watch?v=NUVCQXMUVnI','https://open.spotify.com/track/7KPr0YxECy4Q1k2F17Sa0Q?si=74f750d988014787','default-song.png'),
    ('TheBusiness','Tiesto','INTJ','Stressed','The Business','https://www.youtube.com/watch?v=nCg3ufihKyU','https://open.spotify.com/track/6f3Slt0GbA2bPZlz0aIFXN?si=169f8845359547d2','default-song.png'),
    ('FeelSoClose','Calvin Harris','INTJ','Stressed','18 Months','https://www.youtube.com/watch?v=dGghkjpNCQ8','https://open.spotify.com/track/1gihuPhrLraKYrJMAEONyc?si=da78b4a0f5e843a0','default-song.png'),
    ('GoodFeeling','Flo Rida','INTJ','Happy','Wild Ones','https://www.youtube.com/watch?v=3OnnDqH6Wj8','https://open.spotify.com/track/2LEF1A8DOZ9wRYikWgVlZ8?si=67f4252d89ec4563','default-song.png'),
    ('SafeAndSound','Capital Cities','INTJ','Happy','In A Tidal Wave Of mystery','https://www.youtube.com/watch?v=47dtFZ8CFo8','https://open.spotify.com/track/6Z8R6UsFuGXGtiIxiD8ISb?si=fe751870211e4c73','default-song.png'),
    ('Levels','Avicii','INTJ','Happy','True','https://www.youtube.com/watch?v=_ovdm2yX4MA','https://open.spotify.com/track/5B03nSG8pLE48jh7kmasuL?si=c81432de027c4c76','default-song.png'),
    ('YouandMeFlumeRemix','Disclosure, Eliza Doolittle, Flume','INTJ','Happy','Settle','https://www.youtube.com/watch?v=OUkkaqSNduU','https://open.spotify.com/track/3W2ZcrRsInZbjWylOi6KhZ?si=a6de998b79584be1','default-song.png'),
    ('Passionfruit','Drake','ESTP','Stressed','More Life','https://www.youtube.com/watch?v=COz9lDCFHjw','https://open.spotify.com/track/5mCPDVBb16L4XQwDdbRUpz?si=4b76b2aea9dd4126','default-song.png'),
    ('Headlines','Drake','ESTP','Stressed','Take Care','https://www.youtube.com/watch?v=Sn3SUnL44w4','https://open.spotify.com/track/6LxSe8YmdPxy095Ux6znaQ?si=13f57c5df3e44011','default-song.png'),
    ('Father Stretch My Hands Pt1','Kanye West','ESTP','Neutral','The Life Of Pablo','https://www.youtube.com/watch?v=wuO4_P_8p-Q','https://open.spotify.com/track/4KW1lqgSr8TKrvBII0Brf8?si=7be439a48d6044ec','default-song.png'),
    ('Ms.Jackson','Outkast','ESTP','Happy','Stankonia','https://www.youtube.com/watch?v=CSD2J8yaMmM','https://open.spotify.com/track/0I3q5fE6wg7LIfHGngUTnV?si=51cf81dd3d8a432a','default-song.png'),
    ('Can''t Tell Me Nothing','Kanye West','ESTP','Angry','Graduation','https://www.youtube.com/watch?v=Vcljvd4Ef_o','https://open.spotify.com/track/0mEdbdeRFQwBhN4xfyIeUM?si=ba0d0c586f9d4b85','default-song.png'),
    ('Money Trees','Kendrick Lamar','ESTP','Stressed','good kid, m.A.A.d city','https://www.youtube.com/watch?v=HJNa9Ih3haA','https://open.spotify.com/track/2HbKqm4o0w5wEeEFXm2sD4?si=502ffd0ac76e45e8','default-song.png'),
    ('04:44:00','Jay Z','ESTP','Stressed','04:44:00','https://www.youtube.com/watch?v=UMqr0NjQprE','https://open.spotify.com/track/1gT5TGwbkkkUliNzHRIGi1?si=6e5ea7d630a94020','default-song.png'),
    ('Best I Ever Had','Drake','ESTP','Stressed','So Far Gone','https://www.youtube.com/watch?v=Zfp3KfYH0xA','https://open.spotify.com/track/3QLjDkgLh9AOEHlhQtDuhs?si=cf48932b39dd4be5','default-song.png'),
    ('Bound 2','Kanye West','ESTP','Neutral','Yeezus','https://www.youtube.com/watch?v=BBAtAM7vtgc','https://open.spotify.com/track/3sNVsP50132BTNlImLx70i?si=e67505656cea4f24','default-song.png'),
    ('No Role Modelz','J Cole','ESTP','Stressed','2014 Forest Hills Drive','https://www.youtube.com/watch?v=8HBcV0MtAQg','https://open.spotify.com/track/68Dni7IE4VyPkTOH9mRWHr?si=f39b78d2112544bd','default-song.png'),
    ('Heartless','Kanye West','ESTP','Stressed','808s and Heartbreak','https://www.youtube.com/watch?v=Co0tTeuUVhU','https://open.spotify.com/track/4EWCNWgDS8707fNSZ1oaA5?si=3bf22a928f07446a','default-song.png'),
    ('Pursuit Of Happiness','Kid Cudi','ESTP','Stressed','Man On The Moon: The End Of Day','https://www.youtube.com/watch?v=7xzU9Qqdqww','https://open.spotify.com/track/6MtKObWYda2qnNIpJI21uD?si=374b81bd62a2497b','default-song.png'),
    ('The Heart Part 5','Kendrick Lamar','ESTP','Angry','The Heart Part 5','https://www.youtube.com/watch?v=uAPUkgeiFVY','https://open.spotify.com/track/5MMW4CZsZiZt2iuqAXzzWC?si=9bc349b1446844b9','default-song.png'),
    ('3005','Childish Gambino','ESTP','Happy','Because the Internet','https://www.youtube.com/watch?v=EIRguVEYPeQ','https://open.spotify.com/track/2ZltjIqztEpZtafc8w0I9t?si=b4e1766bd670441e','default-song.png'),
    ('Feels','Calvin Harris, Pharrell Williams, Katy Perry, Big Sean, Funk Wav','ESFP','Happy','Funk Wav Bounces Vol.1','https://www.youtube.com/watch?v=ozv4q2ov3Mk','https://open.spotify.com/track/5bcTCxgc7xVfSaMV3RuVke?si=0c77b16bc65c4b33','default-song.png'),
    ('Levitating','Dua Lipa, DaBaby','ESFP','Happy','Future Nostalgia','https://www.youtube.com/watch?v=N000qglmmY0','https://open.spotify.com/track/5nujrmhLynf4yMoMtj8AQF?si=d0fe5b5996c6459d','default-song.png'),
    ('Don''t Start Now','Dua Lipa','ESFP','Happy','Future Nostalgia','https://www.youtube.com/watch?v=oygrmJFKYZY','https://open.spotify.com/track/3PfIrDoz19wz7qK7tYeu62?si=f68e7df4559d4405','default-song.png'),
    ('New Rules','Dua LIpa','ESFP','Happy','Dua Lipa','https://www.youtube.com/watch?v=AyWsHs5QdiY','https://open.spotify.com/track/2xJCMIJfcNYDc5iR0sAm2O?si=69c17efec1b34b26','default-song.png'),
    ('INDUSTRYBABY','Lil Nas X, Jack Harlow','ESFP','Happy','MONTERO','https://www.youtube.com/watch?v=UTHLKHL_whs','https://open.spotify.com/track/5Z9KJZvQzH6PFmb8SNkxuk?si=ce03edb1b6be41c1','default-song.png'),
    ('Just A Cloud Away','Pharrell Williams','ESFP','Happy','Just A Cloud Away','https://www.youtube.com/watch?v=reYRmpiVSyA','https://open.spotify.com/track/0DGTcMqvVR7fmBXgiG6jz4?si=ad55eb37b7394e53','default-song.png'),
    ('Kiss Me More','Doja Cat, SZA','ESFP','Happy','Planet Her','https://www.youtube.com/watch?v=BhMC23ll2Rk','https://open.spotify.com/track/3DarAbFujv6eYNliUTyqtz?si=c7b51800eddf4661','default-song.png'),
    ('Woman','Doja Cat','ESFP','Happy','Planet Her','https://www.youtube.com/watch?v=2V_uAAAH-_Q','https://open.spotify.com/track/6Uj1ctrBOjOas8xZXGqKk4?si=e94f931ccf7e412e','default-song.png'),
    ('Good4u','Olivia Rodrigo','ESFP','Angry','SOUR','https://www.youtube.com/watch?v=Bc9ijogGmtU','https://open.spotify.com/track/4ZtFanR9U6ndgddUvNcjcG?si=bf0e616d9ebc4398','default-song.png'),
    ('Watermelon Sugar','Harry Styles','ESFP','Neutral','Fine Line','https://www.youtube.com/watch?v=7-x3uD5z1bQ','https://open.spotify.com/track/6UelLqGlWMcVH1E5c4H7lY?si=d92f6c289a054acf','default-song.png'),
    ('Peaches','Justin Bieber, Daniel Caesar, Giveon','ESFP','Stressed','Justice','https://www.youtube.com/watch?v=5rnawnfK2sQ','https://open.spotify.com/track/4iJyoBOLtHqaGxP12qzhQI?si=40ca2e78e2184603','default-song.png'),
    ('Say So','Doja Cat','ESFP','Happy','Hot Pink','https://www.youtube.com/watch?v=uAYG46w1SCA','https://open.spotify.com/track/3Dv1eDb0MEgF93GpLXlucZ?si=cf62ba8be97b445e','default-song.png'),
    ('We''re Good','Dua Lipa','ESFP','Happy','Future Nostalgia','https://www.youtube.com/watch?v=VwDTp0QTyY0','https://open.spotify.com/track/1diS6nkxMQc3wwC4G1j0bh?si=fd3e5230116a405a','default-song.png'),
    ('Sugar','Maroon 5','ESFP','Neutral','V','https://www.youtube.com/watch?v=k8f4lcwKz6g','https://open.spotify.com/track/2iuZJX9X9P0GKaE93xcPjk?si=3f7230c7da5d4423','default-song.png'),
    ('hotgirlbummer','blackbear','ESFP','Angry','hot girl bummer','https://www.youtube.com/watch?v=yMlKJGKyoCo','https://open.spotify.com/track/7aiClxsDWFRQ0Kzk5KI5ku?si=11720460af83447c','default-song.png'),
    ('Congratulations','Post Malone, Quavo','ESFP','Stressed','Stoney','https://www.youtube.com/watch?v=FFhGqNa-Waw','https://open.spotify.com/track/3a1lNhkSLSkpJE4MSHpDu9?si=1211f5d84d794ae8','default-song.png'),
    ('Heat Waves','Glass Animals','ESFP','Stressed','Dreamland','https://www.youtube.com/watch?v=KT7F15T9VBI','https://open.spotify.com/track/3USxtqRwSYz57Ewm6wWRMp?si=39dba5ac306548f8','default-song.png'),
    ('Starboy','The Weeknd, Daft Punk','ESFP','Stressed','Starboy','https://www.youtube.com/watch?v=3_g2un5M350','https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB?si=6b7f404d93a046af','default-song.png'),
    ('Get Lucky','Daft Punk, Pharrel Williams,, Nile Rodgers','ESFP','Stressed','Get Lucky','https://www.youtube.com/watch?v=5NV6Rdv1a3I','https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof?si=8b5b6682ffc74302','default-song.png'),
    ('Back In Black','AC/DC','ESTJ','Angry','Back in Black','https://www.youtube.com/watch?v=pAgnJDJN4VA','https://open.spotify.com/track/08mG3Y1vljYA6bvDt4Wqkj?si=57b8d7e1f39b485e','default-song.png'),
    ('Thunderstruck','AC/DC','ESTJ','Angry','The Razors Edge','https://www.youtube.com/watch?v=v2AC41dglnM','https://open.spotify.com/track/57bgtoPSgt236HzfBOd8kj?si=0b74177a95d24a58','default-song.png'),
    ('T.N.T','AC/DC','ESTJ','Angry','High Voltage','https://www.youtube.com/watch?v=NhsK5WExrnE','https://open.spotify.com/track/7LRMbd3LEoV5wZJvXT1Lwb?si=f21c846bf87c44a4','default-song.png'),
    ('Highway to Hell','AC/DC','ESTJ','Angry','Highway to Hell','https://www.youtube.com/watch?v=l482T0yNkeo','https://open.spotify.com/track/2zYzyRzz6pRmhPzyfMEC8s?si=65e867409bad478c','default-song.png'),
    ('Sweet Child O'' Mine','Guns N'' Roses','ESTJ','Neutral','Appetite For Destruction','https://www.youtube.com/watch?v=1w7OgIMMRc4','https://open.spotify.com/track/7snQQk1zcKl8gZ92AnueZW?si=12605b7f3524492b','default-song.png'),
    ('Welcome To The Jungle','Guns N'' Roses','ESTJ','Angry','Appetite For Destruction','https://www.youtube.com/watch?v=o1tj2zJ2Wvg','https://open.spotify.com/track/0G21yYKMZoHa30cYVi1iA8?si=4b8dc461515245e9','default-song.png'),
    ('Walk This Way','Aerosmith','ESTJ','Neutral','Toys In The Attic','https://www.youtube.com/watch?v=4c8O2n1Gfto','https://open.spotify.com/track/5SZ6zX4rOrEQferfFC2MfP?si=5e155dd154f54b4a','default-song.png'),
    ('Rock And Roll All Nite','KISS','ESTJ','Happy','Dressed To Kill','https://www.youtube.com/watch?v=f-S3X2saSwM','https://open.spotify.com/track/6KTv0Z8BmVqM7DPxbGzpVC?si=ffba54a25fae47f3','default-song.png'),
    ('Crazy Train','Ozzy Osbourne','ESTJ','Angry','Blizzard Of Ozz','https://www.youtube.com/watch?v=FVovq9TGBw0','https://open.spotify.com/track/7ACxUo21jtTHzy7ZEV56vU?si=9f3e9e516e9247ac','default-song.png'),
    ('Smells Like Teen Spirit','Nirvana','ESTJ','Stressed','Nevermind','https://www.youtube.com/watch?v=hTWKbfoikeg','https://open.spotify.com/track/5ghIJDpPoe3CfHMGu71E6T?si=c6b3296488254d25','default-song.png'),
    ('Another One Bites The Dust','Queen','ESTJ','Neutral','The Game','https://www.youtube.com/watch?v=PqUenEMwsdQ','https://open.spotify.com/track/57JVGBtBLCfHw2muk5416J?si=5d3fb41e4a1f4c6a','default-song.png'),
    ('Livin'' On A Prayer','Bon Jovi','ESTJ','Stressed','Slippery When Wet','https://www.youtube.com/watch?v=lDK9QqIzhwk','https://open.spotify.com/track/0J6mQxEZnlRt9ymzFntA6z?si=f65d3768109d4911','default-song.png'),
    ('Kickstart My Heart','Motley Crue','ESTJ','Angry','Dr.Feelgood','https://www.youtube.com/watch?v=mVurA44hwiw','https://open.spotify.com/track/7GonnnalI2s19OCQO1J7Tf?si=7207cb246fdb4ea4','default-song.png'),
    ('I Was Made For Lovin'' You','KISS','ESTJ','Stressed','Dynasty','https://www.youtube.com/watch?v=ZhIsAZO5gl0','https://open.spotify.com/track/07q0QVgO56EorrSGHC48y3?si=2882e19244d34497','default-song.png'),
    ('Barracuda','Heart','ESTJ','Angry','Little Queen','https://www.youtube.com/watch?v=VdOkQ6THDVw','https://open.spotify.com/track/4KfSdst7rW39C0sfhArdrz?si=8d9ee78679774c0e','default-song.png'),
    ('The Barber of Seville','Gioachino Rossini','ISTJ','Neutral','Rossini - Ouvertures','https://www.youtube.com/watch?v=OloXRhesab0','https://open.spotify.com/track/3PGPfeQTaZgHnmofWYBHSW?si=9ceb3c271b074224','default-song.png'),
    ('Nocturne in B flat minor','Frederic Chopin','ISTJ','Stressed','Chopin: Nocturnes','https://www.youtube.com/watch?v=t-JD2bnNQvY','https://open.spotify.com/track/2KvwdV2iYrOuSyNJ31P5bH?autoplay=true','default-song.png'),
    ('Nocturne in E Flat Major','Frederic Chopin','ISTJ','Stressed','Chopin: Nocturnes','https://www.youtube.com/watch?v=9E6b3swbnWg','https://open.spotify.com/track/1VNvsvEsUpuUCbHpVop1vo?si=6c61e3d9175a4734','default-song.png'),
    ('Waltz in A minor','Frederic Chopin','ISTJ','Stressed','Chopin: Waltzes, etc.','https://www.youtube.com/watch?v=algM0c_u99k','https://open.spotify.com/track/0aJDvIeUkceMRueD84rRDR','default-song.png'),
    ('Piano Concerto No.21','Wolfgang Mozart','ISTJ','Stressed','Mozart: Piano Concertos, Vol. 6','https://www.youtube.com/watch?v=df-eLzao63I','https://open.spotify.com/track/01QJ0UbSTP9Y49R4Q9qiFs','default-song.png'),
    ('The Well Tempered Clavier','J.S.Bach','ISTJ','Stressed','The Well Tempered Clavier Book 1','https://www.youtube.com/watch?v=ezZdbzreNcs','https://open.spotify.com/track/2XxC430QMotGdympDP1aBo?si=9193d8c997364d76','default-song.png'),
    ('Arabesque No.1','Debussy','ISTJ','Stressed','Debussy, C.:Piano Music (Complete), Vol. 3-Suite Bergamasque/Children''s Corner','https://www.youtube.com/watch?v=Yh36PaE-Pf0','https://open.spotify.com/track/1btSclzWM6mSKy0pFACPCZ?si=5c3fa9f7e4ee4b07','default-song.png'),
    ('Fracture','Stephan Moccio','ISTJ','Stressed','Fracture','https://www.youtube.com/watch?v=hYH80WGPet8','https://open.spotify.com/track/2m2GJpBjQNNphaCgBeoj7R?si=d98f82149cc0402e','default-song.png'),
    ('Clair de Lune','Claude Debrussy','ISTJ','Stressed','Debussy, Clair De Lune and Other Piano Favourites','https://www.youtube.com/watch?v=CvFH_6DNRCY','https://open.spotify.com/track/5u5aVJKjSMJr4zesMPz7bL?si=49ef37c460b74804','default-song.png'),
    ('2 Melodies','Anton Rubinstein','ISTJ','Happy','Romantic Piano favourites, Vol 1.','https://www.youtube.com/watch?v=N2UJXn0fNi4','https://open.spotify.com/track/292v462HzpqvKNha41SiWZ','default-song.png'),
    ('String Quartet in F Minor','Joseph Haydn','ISTJ','Angry','The Haydn Project','https://www.youtube.com/watch?v=s9olhyCmosw','https://open.spotify.com/track/3F1KgQJoI75WV9DSDJmKv0','default-song.png'),
    ('Cello Suite No. 1 in G Major','J.S.Bach','ISTJ','Happy','Bach: Cello Suites Nos. 1,5 and 6','https://www.youtube.com/watch?v=1prweT95Mo0','https://open.spotify.com/track/17i5jLpzndlQhbS4SrTd0B?si=7b6b3567558648bd','default-song.png'),
    ('No. 24 in A Minor','24 Caprices','ISTJ','Angry','Paganini: 24 Caprices','https://www.youtube.com/watch?v=r0m21rGZXx8','https://open.spotify.com/track/6cC6h5E351deEGFd7Kh9uy','default-song.png');