CREATE DATABASE IF NOT EXISTS COMP2800;
        use COMP2800;
        CREATE TABLE IF NOT EXISTS BBY_8_user (
            ID int NOT NULL AUTO_INCREMENT,
            firstName varchar(30),
            lastName varchar(30),
            email varchar(30),
            password varchar(30),
            role char,
            userName varchar(30),
            age int,
            personality varchar(30),
            filesrc varchar (100),
            PRIMARY KEY (ID)
        );
        use COMP2800;
        CREATE TABLE IF NOT EXISTS BBY_8_survey (
            userID int NOT NULL,
            dateOfSurvey DATE,
            survey varchar(30),
            PRIMARY KEY (userID, dateOfSurvey),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS BBY_8_album (
            ID int NOT NULL AUTO_INCREMENT,
            title varchar(30), 
            artist varchar(30),
            genre varchar(30),
            dateofRelease DATE,
            filesrc varchar (100),
            PRIMARY KEY (ID)
        );
        CREATE TABLE IF NOT EXISTS BBY_8_song (
            ID int NOT NULL AUTO_INCREMENT,
            title varchar(50),
            artist varchar(80),
            personality varchar(4),
            mood varchar(30), 
            album varchar(80),
            youtubeLink varchar(70),
            spotifyLink varchar(80),
            filesrc varchar (100),            
            PRIMARY KEY (ID)
        );
        CREATE TABLE IF NOT EXISTS BBY_8_library (
            userID int NOT NULL,
            songID int NOT NULL,
            PRIMARY KEY (userID, songID),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID) ON DELETE CASCADE,
            FOREIGN KEY (songID) REFERENCES BBY_8_song(ID) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS BBY_8_review (
            userID int NOT NULL,
            songID int NOT NULL,
            dateOfReview DATE,
            review varchar(150),
            PRIMARY KEY (userID, songID, dateOfReview),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID) ON DELETE CASCADE,
            FOREIGN KEY (songID) REFERENCES BBY_8_song(ID) ON DELETE CASCADE
        );
        CREATE TABLE IF NOT EXISTS BBY_8_post (
			ID int NOT NULL AUTO_INCREMENT,
            userID int NOT NULL,
            dateOfPost DATETIME,
            post varchar(150),
            filesrc varchar (100),
            PRIMARY KEY (ID),
            FOREIGN KEY (userID) REFERENCES BBY_8_user(ID) ON DELETE CASCADE
        );
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("John", "Smith", "JS@test.ca", "1234", 'A', "JohnCena420", "69", "INFJ", "default");
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("Jason", "Turner", "jasonTurn@tec.ca", "4312", 'R', "JasonSparrow", "34", "ENFJ", "default");
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("Amy", "Santiago", "AMS@brook.ca", "JQRIBVQIX23", 'R', "TheTerminator", "30", "INTP", "default");
INSERT INTO BBY_8_user (firstName, lastname, email, password, role, userName, age, personality, filesrc)
    VALUES ("Diego", "Cuenca Espino", "dce@my.bcit.ca", "notabc123", 'A', "DCE", "21", "INTP", "default");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Depression Cherry", "Beach House", "Dream Pop", "2015-08-28", "beach-house-depression-cherry.png");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Thank Your Lucky Stars", "Beach House", "Dream Pop", "2015-10-16", "beach-house-thank-your.png");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Fuzzybrain", "Dayglow", "Indie Pop", "2018-09-28", "hot-rod-dayglow.jpg");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("Appetite for Destruction", "Guns N' Roses", "Hard Rock", "1987-07-21", "guns-n-roses-appetite.jpg");
INSERT INTO BBY_8_album (title, artist, genre, dateofRelease, filesrc)
    VALUES ("True", "Avicii", "EDM", "2013-09-13", "avicii-true.jpg");
INSERT INTO BBY_8_song (title, artist, personality, mood, album, youtubeLink, spotifyLink, filesrc)
    VALUES ("Bach: Cello Suite No.! in G Major", "Yo-Yo Ma", "ISTJ", "TBD", "Six Suites for Unaccompanied Cello", "https://youtu.be/pAgnJDJN4VA?list=PLv5D2n4QoJbrgC3LQo9PAzTZccsgDANBh", "https://open.spotify.com/track/7sjuI9Y9rsrWOJUNVzqOK7?autoplay=true", "bach-cello-yo-yo-ma.jpg");
INSERT INTO BBY_8_song (title, artist, personality, mood, album, youtubeLink, spotifyLink, filesrc)
    VALUES ("Nocturne op.9 No.2", "Chopin", "ISTJ", "TBD", "Chopin: Nocturnes", "https://www.youtube.com/watch?v=9E6b3swbnWg", "https://open.spotify.com/track/61dYvvfIRtIDFuqZypPAta", "nocturne-chopin.jpg");
INSERT INTO BBY_8_song (title, artist, personality, mood, album, youtubeLink, spotifyLink, filesrc)
    VALUES
    ('Space Song','Beach House','ENFJ','stressed','Depression Cherry','https://www.youtube.com/watch?v=RBtlPT23PTM','https://open.spotify.com/track/7H0ya83CMmgFcOhw0UB6ow?si=58caf26bc2d64dc5','beach-house-depression-cherry.png'),
    ('Myth','Beach House','ENFJ','stressed','Bloom','https://www.youtube.com/watch?v=FuvWc3ToDHg','https://open.spotify.com/track/2NfxtzCIrpCmJX5Z2KMdD5?si=6fd60bbfba264f3a','beach-house-myth.jpg'),
    ('Pretty Girl','Clairo','ENFJ','stressed','Pretty Girl','https://www.youtube.com/watch?v=mngtcfcaVrI','https://open.spotify.com/track/0KyAGiNGUytG5JLxJu4F6l?si=d9c07d6ed1724237','pretty-girl-clairo.jpg'),
    ('Hot Rod','Dayglow','ENFJ','stressed','Fuzzybrain','https://www.youtube.com/watch?v=RUih0WRFI-g','https://open.spotify.com/track/12j3KX5TkcAswLUUPMTNqA?si=144727caaba74c1e','hot-rod-dayglow.jpg'),
    ('Can I Call You Tonight','Dayglow','ENFJ','stressed','Fuzzybrain','https://www.youtube.com/watch?v=hh1WeQxfCX0','https://open.spotify.com/track/5Ti99QiUdIwe0xG4gS22FL?si=4bf1bca88eb64f51','can-i-call-you-tonight-dayglow.jpg'),
    ('Motion Sickness','Phoebe Bridgers','ENFJ','stressed','Stranger in the Alps','https://www.youtube.com/watch?v=9sfYpolGCu8','https://open.spotify.com/track/6LxcPUqx6noURdA5qc4BAT?si=0d72e75851ae461a','motion-sickness-phoebe.jpg'),
    ('Heather','Conan Gray','ENFJ','stressed','Kid Krow','https://www.youtube.com/watch?v=24u3NoPvgMw','https://open.spotify.com/track/4xqrdfXkTW4T0RauPLv3WA?si=6c56af70621c458f','heather-conan-gray.jpg'),
    ('Sunflower','Rex Orange County','ENFJ','stressed','Sunflower','https://www.youtube.com/watch?v=V0X-SWiDr1g','https://open.spotify.com/track/4EpZ4eYuZOwPSSwyqpdHnJ?si=979e63a8fc0a4550','sunflower-rex-orange.jpg'),
    ('Pluto Projector','Rex Orange County','ENFJ','stressed','Pony','https://www.youtube.com/watch?v=Pi9J4epTWGM','https://open.spotify.com/track/4EWBhKf1fOFnyMtUzACXEc?si=aae4be632a12479f','pluto-projector-rex-orange.jpg'),
    ('Cigarette Daydreams','Cage The Elephant','ENFJ','stressed','Melophobia','https://www.youtube.com/watch?v=D9qhL-RckVA','https://open.spotify.com/track/2tznHmp70DxMyr2XhWLOW0?si=1d53f49fa78e487c','cigarette-daydreams-cage.jpg'),
    ('Dark Red','Steve Lacy','ENFJ','stressed','Dark Red','https://www.youtube.com/watch?v=xRzbLQ_WKPs','https://open.spotify.com/track/37y7iDayfwm3WXn5BiAoRk?si=e7a0e11db3ac4fe1','dark-red-steve-lacy.jpg'),
    ('Peach Pit','Peach Pit','ENFJ','neutral','Sweet FA','https://www.youtube.com/watch?v=p4y4eT1cJ54','https://open.spotify.com/track/0ZK8TGOsngrstVPsnrHbK1?si=07808b7c2ee442dc','peach-pit.jpg'),
    ('BESTINTEREST','Tyler, The Creator','ENFJ','happy','BEST INTEREST','https://www.youtube.com/watch?v=NkMTKGM-efw','https://open.spotify.com/track/3jHdKaLCkuNEkWcLVmQPCX?si=5fa9ef9882984a74','best-interest-tyler.jpg'),
    ('3 Nights','Dominic FIke','ENFJ','stressed','Don''t Forget About Me, Demos','https://www.youtube.com/watch?v=OWKzRngush4','https://open.spotify.com/track/1tNJrcVe6gwLEiZCtprs1u?si=3e8373d529324b06','3-nights-dominic.jpg'),
    ('Homage','Mild High Club','ENFJ','neutral','Skiptracing','https://www.youtube.com/watch?v=Yv3OFuzYWDU','https://open.spotify.com/track/7pegxVesMmE2qK0o58xoFG?si=6aae0fddcb114cd3','mild-high-club-homage.jpg'),
    ('Boredom','Tyler, The Creator','ENFJ','stressed','FlowerBoy','https://www.youtube.com/watch?v=jxlBOBOZHqI','https://open.spotify.com/track/5WNYg3usc6H8N3MBEp4zVk?si=6a9dd4e7af7f4190','boredom-tyler.jpg'),
    ('No Surprises','Radiohead','INTP','neutral','OK Computer','https://www.youtube.com/watch?v=u5CVsCnxyXg','https://open.spotify.com/track/10nyNJ6zNy2YVYLrcwLccB?si=42d4fe6846194e36','no-surprises-radiohead.jpg'),
    ('Weird Fishes/Arpeggi','Radiohead','INTP','neutral','In Rainbows','https://www.youtube.com/watch?v=V_Ydoe4Q-Gg','https://open.spotify.com/track/4wajJ1o7jWIg62YqpkHC7S?si=74af5808f9c74dca','weird-fishes-radiohead.jpg'),
    ('I Miss You','blink-182','INTP','neutral','Blink182','https://www.youtube.com/watch?v=s1tAYmMjLdY','https://open.spotify.com/track/5glvnkBJ4sLrObTyprSsPg?si=d0816f8995d74e9c','i-miss-you-blind182.jpg'),
    ('Island In The Sun','Weezer','INTP','neutral','Smallville:The Talon Mix','https://www.youtube.com/watch?v=erG5rgNYSdk','https://open.spotify.com/track/1IRZwD3r9VOehOR8rGeV3Y?si=e8c6b25289224c93','island-in-the-sun-weezer.jpg'),
    ('The Man Who Sold The World','Nirvana','INTP','stressed','MTV Unplugged In NewYork','https://www.youtube.com/watch?v=fregObNcHC8','https://open.spotify.com/track/48psxWnIVYCPUZJKiuDiEf?si=da0af95eaf3846cd','the-man-who-sold-the-world-nirvana.jpg'),
    ('Exit Music For A Film','Radiohead','INTP','neutral','OK Computer','https://www.youtube.com/watch?v=Bf01riuiJWA','https://open.spotify.com/track/0z1o5L7HJx562xZSATcIpY?si=44a44768b08345ec','exit-music-for-a-film-radiohead.jpg'),
    ('Sunday Morning','The Velvet Underground, Nico','INTP','happy','The Velvet Underground and Nico','https://www.youtube.com/watch?v=Xhbyj8pqUao','https://open.spotify.com/track/11607FzqoipskTsXrwEHnJ?si=7ec6b48ceb034b91','sunday-morning-the-velvet-underground.jpg'),
    ('Femme Fatale','The Velvet Underground, Nico','INTP','happy','The Velvet Underground and Nico','https://www.youtube.com/watch?v=3wNNG49Jz48','https://open.spotify.com/track/3PG7BAJG9WkmNOJOlc4uAo?si=58bffadfcf0c453b','femme-fatale-the-velvet-underground-jpg'),
    ('She Brings The Rain','CAN','INTP','stressed','Soundtracks','https://www.youtube.com/watch?v=3wNNG49Jz48','https://open.spotify.com/track/798UQDI0kkPc562NvOZ163?si=9c03778c846c4214','she-brings-the-rain-can.jpg'),
    ('Moonshake','CAN','INTP','neutral','Future Days','https://www.youtube.com/watch?v=JAdNjKAAj_o','https://open.spotify.com/track/6ACXIPu0jhLDriV5sjrWtb?si=34dd75ecf48e4358','moon-shake-can.jpg'),
    ('Singapore','Tom Waits','INTP','happy','Rain Dogs','https://www.youtube.com/watch?v=DfvASyLcKs4','https://open.spotify.com/track/1NmUM1cIycWhgSz1qKmCXh?si=900867e598ff4cc1','singapore-tom-waits.jpg'),
    ('Downtown Train','Tom Waits','INTP','stressed','Rain Dogs','https://www.youtube.com/watch?v=qWDJIwqCXi4','https://open.spotify.com/track/3fPqUl4lPDUQmY0T7dKUv2?si=5d29c4d0c6ae475b','singapore-tom-waits.jpg'),
    ('Paper Hats','This Heat','INTP','angry','Deceit','https://www.youtube.com/watch?v=DkiK_YHxv0I','https://open.spotify.com/track/0XqKAig27dZT9AXcup5Zj0?si=98a19e96e908448a','paper-hats-this-heat.jpg'),
    ('Silence','Portishead','INTP','neutral','Third','https://www.youtube.com/watch?v=0Y35MdpqMRk','https://open.spotify.com/track/6CLLkUajKRN9LS9PeK3OZF?si=923818b57caf46c9','silence-portishead.jpg'),
    ('The Rip','Portishead','INTP','stressed','Third','https://www.youtube.com/watch?v=kBOaLjtR4mw','https://open.spotify.com/track/5KX2DSPC6aCA0pdDidTmBC?si=f5f128a241934129','the-rip-portishead.jpg'),
    ('Hey','Pixies','INTP','neutral','Doolittle','https://www.youtube.com/watch?v=tVCUAXOBF7w','https://open.spotify.com/track/0p5eZCY0R7uNCZS1YDtIYI?si=79f31991ea3a46e7','hey-pixies.jpg'),
    ('All The Small Things','blink-182','ENTP','neutral','Enema Of The State','https://www.youtube.com/watch?v=9Ht5RZpzPqw','https://open.spotify.com/track/7yCPwWs66K8Ba5lFuU2bcx?si=59940ff992fd4563','all-the-small-things.jpg'),
    ('Teenagers','My Chemical Romance','ENTP','happy','The Black Parade','https://www.youtube.com/watch?v=k6EQAOmJrbw','https://open.spotify.com/track/7j31rVgGX9Q2blT92VBEA0?si=84bb8bc179a94ef0','teenagers.jpg'),
    ('Welcome to the Black Parade','My Chemical Romance','ENTP','stessed','The Black Parade','https://www.youtube.com/watch?v=RRKJiM9Njr8','https://open.spotify.com/track/5wQnmLuC1W7ATsArWACrgW?si=af18880e77bc455b','welcome-to-the-black-parade.jpg'),
    ('Hash Pipe','Weezer','ENTP','angry','Weezer (GreenAlbum)','https://www.youtube.com/watch?v=_9BGLtqqkVI','https://open.spotify.com/track/29xKs5BAHlmlX1u4gzQAbJ?si=d16596cf590246c7','hash-pipe.jpg'),
    ('Basket Case','Green Day','ENTP','happy','Dookie','https://www.youtube.com/watch?v=NUTGr5t3MoY','https://open.spotify.com/track/6L89mwZXSOwYl76YXfX13s?si=2bc2869201874df2','basket-case.jpg'),
    ('Sugar, We''re Goin Down','Fall Out Boy','ENTP','neutral','From Under The Cork Tree','https://www.youtube.com/watch?v=uhG-vLZrb-g','https://open.spotify.com/track/2TfSHkHiFO4gRztVIkggkE?si=34936db55c1f4aae','sugar-were-goin-down.jpg'),
    ('Stacy''s Mom','Fountains Of Wayne','ENTP','happy','Welcome Interstate Managers','https://www.youtube.com/watch?v=dZLfasMPOU4','https://open.spotify.com/track/27L8sESb3KR79asDUBu8nW?si=e0ffa103d8a74405','stacys-mom.jpg'),
    ('Time Bomb','Rancid','ENTP','happy','...And Out Come The Wolves','https://www.youtube.com/watch?v=DhKHAopx7D0','https://open.spotify.com/track/7goMqXhydyyhmWdPxLTm7E?si=002900dd2c2c4a45','time-bomb.jpg'),
    ('I Was Wrong','Social Distortion','ENTP','neutral','White Light White Heat White Trash','https://www.youtube.com/watch?v=aXAU4MmMIMo','https://open.spotify.com/track/1Lpmme6uCsPJIdcbR5aePx?si=e72617fbd58d4aab','i-was-wrong.jpg'),
    ('London Calling','The Clash','ENTP','angry','London Calling','https://www.youtube.com/watch?v=EfK-WX2pa8c','https://open.spotify.com/track/5jzma6gCzYtKB1DbEwFZKH?si=e440899a3e9d4f7d','london-calling.jpg'),
    ('Train in Vain','The Clash','ENTP','happy','London Calling','https://www.youtube.com/watch?v=zqZSONJYNGI','https://open.spotify.com/track/6ITuEsxEy2qPhqMowdDAeI?si=bbb4279c71e04757','train-in-vain.jpg'),
    ('California Uber Alles','Dead Kennedys','ENTP','angry','Give Me Convenience or Give Me Death','https://www.youtube.com/watch?v=jrWflCJPM4w','https://open.spotify.com/track/5szJ8SMwQVEvvdk65w6M6g?si=e6661aacea224bb2','california-uber-alles.jpg'),
    ('Holiday in Cambodia','Dead Kennedys','ENTP','angry','Fresh Fruit For Rotting Vegetables','https://www.youtube.com/watch?v=Qr6NOsluHYg','https://open.spotify.com/track/6ZR7gzHIvcj4qvo5q4kqXN?si=5312ed4a4a1045ea','holiday-in-cambodia.jpg'),
    ('Nazi Punks Fuck Off','Dead Kennedys','ENTP','angry','Plastic Surgery Disasters','https://www.youtube.com/watch?v=iyc62g7YQM0','https://open.spotify.com/track/2LF13LC1wG5XqZ2js2yC9O?si=5a8b0208f9e24010','nazi-punks-fuck-off.jpg'),
    ('Too Drunk to Fuck','Dead Kennedys','ENTP','angry','Fresh Fruit For Rotting Vegetables','https://www.youtube.com/watch?v=4ncqvLktdT8','https://open.spotify.com/track/5VTT6Qxr5938lOmStMJXhB?si=9e4ce66ccb934163','too-drunk-to-fuck.jpg'),
    ('Youth of America','Wipers','ENTP','angry','Youth of America','https://www.youtube.com/watch?v=YaUzYISKKAI','https://open.spotify.com/track/2Dj59k8Rar55hTbzwCt2bK?si=c23287f4c8ac4e17','youth-of-america.jpg'),
    ('When It''s Over','Wipers','ENTP','neutral','Youth of America','https://www.youtube.com/watch?v=tUm_FeB0KlQ','https://open.spotify.com/track/59RkLuqY3LSqK3rJGds6cP?si=654588c8490942a7','when-its-over.jpg'),
    ('I Gotta Feeling','Black Eyed Peas','ISFP','happy','The E.N.D','https://www.youtube.com/watch?v=uSD4vsh1zDA','https://open.spotify.com/track/4vp2J1l5RD4gMZwGFLfRAu?si=994df531df61441c','i-gotta-feeling.jpg'),
    ('Party Rock Anthem','LMFAO','ISFP','happy','Sorry For Party Rocking','https://www.youtube.com/watch?v=KQ6zr6kCPj8','https://open.spotify.com/track/7mitXLIMCflkhZiD34uEQI?si=21e980f469394ceb','party-rock-anthem.jpg'),
    ('Like A G6','Far East Movement','ISFP','neutral','Dirty Bass','https://www.youtube.com/watch?v=w4s6H4ku6ZY','https://open.spotify.com/track/2s5YN9O8Qv25BjQobPHWVZ?si=27c9ed687c3b4880','like-a-g6.jpg'),
    ('Head and Heart','Joel Corry','ISFP','happy','Heart and Heart','https://www.youtube.com/watch?v=CRuOOxF-ENQ','https://open.spotify.com/track/6cx06DFPPHchuUAcTxznu9?si=7d45847e0e43457f','head-and-heart.jpg'),
    ('Crazy In Love','Beyonce, Jay-Z','ISFP','happy','Dangerously In Love','https://www.youtube.com/watch?v=ViwtNLUqkMY','https://open.spotify.com/track/5IVuqXILoxVWvWEPm82Jxr?si=8163e16b0b4a4b19','crazy-in-love.jpg'),
    ('Last Friday Night','Kay Perry','ISFP','happy','Teenage Dream','https://www.youtube.com/watch?v=KlyXNRrsk4A','https://open.spotify.com/track/455AfCsOhhLPRc68sE01D8?si=10715267fb3b44a4','last-friday-night.jpg'),
    ('Just Dance','Lady Gaga','ISFP','happy','The Fame','https://www.youtube.com/watch?v=gwrZEmYEotQ','https://open.spotify.com/track/1dzQoRqT5ucxXVaAhTcT0J?si=b933198442704c9a','just-dance.jpg'),
    ('Scream and Shout','will.i.am, Britney Spears','ISFP','stressed','#willpower','https://www.youtube.com/watch?v=kYtGl1dX5qI','https://open.spotify.com/track/2iJuuzV8P9Yz0VSurttIV5?si=1581bf01fc544c8e','scream-and-shout.jpg'),
    ('Hey Ya','Outkast','ISFP','happy','Speakerboxxx/The Love Below','https://www.youtube.com/watch?v=PWgvGjAhvIw','https://open.spotify.com/track/2PpruBYCo4H7WOBJ7Q2EwM?si=5f816175d3644942','hey-ya.jpg'),
    ('Waiting For Love','Avicii','ISFP','neutral','Stories','https://www.youtube.com/watch?v=cHHLHGNpCSA','https://open.spotify.com/track/2P4OICZRVAQcYAV2JReRfj?si=765896efd7f54dec','waiting-for-love.jpg'),
    ('Starships','Nicki Minaj','ISFP','happy','Pink Friday...Roman Reloaded','https://www.youtube.com/watch?v=SeIJmciN8mo','https://open.spotify.com/track/1oHNvJVbFkexQc0BpQp7Y4?si=53c70b6c44304eb7','starships.jpg'),
    ('We Found Love','Rihanna, Calvin Harris','ISFP','stressed','Talk That Talk','https://www.youtube.com/watch?v=tg00YEETFzg','https://open.spotify.com/track/6qn9YLKt13AGvpq9jfO8py?si=cb9c124994724e9d','we-found-love.jpg'),
    ('Timber','Pitbull, Kesha','ISFP','happy','Global Warming:Meltdown','https://www.youtube.com/watch?v=hHUbLv4ThOo','https://open.spotify.com/track/3cHyrEgdyYRjgJKSOiOtcS?si=5479e322ae034ef6','timber.jpg'),
    ('Whistle','Flo Rida','ISFP','happy','Wild Ones','https://www.youtube.com/watch?v=cSnkWzZ7ZAA','https://open.spotify.com/track/3bC1ahPIYt1btJzSSEyyrF?si=dd9944c30bfb44dd','whistle.jpg'),
    ('Don''t Stop The Music','Rihanna','ISFP','happy','Good Girl Gone Bad','https://www.youtube.com/watch?v=yd8jh9QYfEs','https://open.spotify.com/track/0ByMNEPAPpOR5H69DVrTNy?si=e5a5bb681ef9451a','dont-stop-the-music.jpg'),
    ('Toxic','Brittney Spears','ISFP','happy','In The Zone','https://www.youtube.com/watch?v=LOZuxwVk7TU','https://open.spotify.com/track/6I9VzXrHxO9rA9A5euc8Ak?si=157cf35f82a34eec','toxic.jpg'),
    ('Party In The USA','Miley Cyrus','ISFP','happy','The Time Of Our Lives','https://www.youtube.com/watch?v=M11SvDtPBhA','https://open.spotify.com/track/3E7dfMvvCLUddWissuqMwr?si=152842e59a7e497f','party-in-the-usa.jpg'),
    ('Uptown Funk','Bruno Mars','ISFP','happy','Uptown Special','https://www.youtube.com/watch?v=OPf0YbXqDm0','https://open.spotify.com/track/32OlwWuMpZ6b0aN2RZOeMS?si=3a4d741c064e4f9e','uptown-funk.jpg'),
    ('Symptom of the Universe','Black Sabbath','ENTJ','angry','Sabotage','https://www.youtube.com/watch?v=4g_Yk6eKlwk','https://open.spotify.com/track/7lwCPihf6s0609Q5uBjXrF?si=a1693ff693bc4f4c','symptom-of-the-universe.jpg'),
    ('The Trooper','Iron Maiden','ENTJ','angry','Piece of Mind','https://www.youtube.com/watch?v=X4bgXH3sJ2Q','https://open.spotify.com/track/4OROzZUy6gOWN4UGQVaZMF?si=17fac4af9a8d470a','the-trooper.jpg'),
    ('Paranoid','Black Sabbath','ENTJ','angry','Paranoid','https://www.youtube.com/watch?v=0qanF-91aJo','https://open.spotify.com/track/3q9G9SvgdfE1fxlvoDIb20?si=132bbe441a744227','paranoid'),
    ('Crazy Train','Ozzy Osbourne','ENTJ','angry','Blizzard of Ozz','https://www.youtube.com/watch?v=tMDFv5m18Pw','https://open.spotify.com/track/2b9lp5A6CqSzwOrBfAFhof?si=9b9ac96f21d24be8','crazy-train.jpg'),
    ('Master of Puppets','Metallica','ENTJ','angry','Master Of Puppets','https://www.youtube.com/watch?v=0obBdrfUMzU','https://open.spotify.com/track/6NwbeybX6TDtXlpXvnUOZC?si=348b3cbb001d42e2','master-of-puppets.jpg'),
    ('Heaven and Hell','Black Sabbath','ENTJ','stressed','Heaven and Hell','https://www.youtube.com/watch?v=5FRA7UXlGu8','https://open.spotify.com/track/6LtNEH08J18r4HLs4HzvqW?si=a86a1db8bbf845d9','heaven-and-hell.jpg'),
    ('Welcome To The Jungle','Guns N'' Roses','ENTJ','happy','Appetite For Destruction','https://www.youtube.com/watch?v=o1tj2zJ2Wvg','https://open.spotify.com/track/0oWHLtxWeMJhmwxtrxhNK0?si=c8cf1a94f62b4573','welcome-to-the-jungle.jpg'),
    ('Seek and Destroy','Metallica','ENTJ','angry','Kill ''Em All','https://www.youtube.com/watch?v=Wm58sGEdgAw','https://open.spotify.com/track/1LDAh7QQnWvp3GJ9QDa1Pj?si=9ec8451a4ef74938','seek-and-destroy.jpg'),
    ('Runnin'' With The Devil','Van Halen','ENTJ','angry','Van Halen','https://www.youtube.com/watch?v=enL_lzVyNdM','https://open.spotify.com/track/3gLlcZQMvpwgtV9THHXrGp?si=7c34d9292a2041e6','runnin-with-the-devil.jpg'),
    ('Bark at the Moon','Ozzy Osbourne','ENTJ','angry','Bark At The Moon','https://www.youtube.com/watch?v=F89-MOy7Xfg','https://open.spotify.com/track/2E7W1X4maFFcjHrVrFA7Vs?si=b2f9cadd0e0d482f','bark-at-the-moon.jpg'),
    ('Ghost','Nightmares','ENTJ','angry','After Death','https://www.youtube.com/watch?v=4tDwAeCkpho','https://open.spotify.com/track/7kLzH5kMAxvWuqYjGoUX8t?si=179dbb2ebe7b4288','ghost.jpg'),
    ('In the End','Linkin Park','ENTJ','stressed','Hybrid Theory','https://www.youtube.com/watch?v=eVTXPUF4Oz4','https://open.spotify.com/track/3tSmXSxaAnU1EPGKa6NytH?si=ae5b65be7b8b41d5','in-the-end.jpg'),
    ('Hangar 18','Megadeth','ENTJ','angry','Rust In Peace','https://www.youtube.com/watch?v=x5A9Aa-WU5E','https://open.spotify.com/track/6b6uLZsoGhObYexIxnRbIb?si=801b1d6630cc47c9','hangar-18.jpg'),
    ('God''s Country','Blake Shelton','ISFJ','stressed','Fully Loaded:God''s Country','https://www.youtube.com/watch?v=ZEWGyyLiqY4','https://open.spotify.com/track/4TCeFZNjGNQIpCuZmJkkE2?si=d37d42bfb61e45c3','gods-country.jpg'),
    ('Big Iron','Marty Robbins','ISFJ','stressed','Gunfighter Ballads And Trail Songs','https://www.youtube.com/watch?v=zzICMIu5zFY','https://open.spotify.com/track/0AQquaENerGps8BQmbPw14?si=abd7ae1839634f51','big-iron.jpg'),
    ('Jolene','Dolly Parton','ISFJ','stressed','Jolene','https://www.youtube.com/watch?v=Ixrje2rXLMA','https://open.spotify.com/track/2SpEHTbUuebeLkgs9QB7Ue?si=71aed85fa46841ff','jolene.jpg'),
    ('Daddy Sang Bass','Johnny Cash','ISFJ','happy','The Essential Johnny Cash','https://www.youtube.com/watch?v=x_geYBnMNG0','https://open.spotify.com/track/15TITugVC8RrpLctHXOqT8?si=8afbd45c6ff84e1d','daddy-sang-bass.jpg'),
    ('Achy Breaky Heart','Billy Ray Cyrus','ISFJ','happy','Some Gave All','https://www.youtube.com/watch?v=byQIPdHMpjc','https://open.spotify.com/track/2EoIt9vdgFRNW03u5IvFsQ?si=8bd89b6039e54b2c','achy-breaky-heart.jpg'),
    ('Chicken Fried','Zac Brown Band','ISFJ','happy','The Foundation','https://www.youtube.com/watch?v=e4ujS1er1r0','https://open.spotify.com/track/3eBnEo9WL34ulBCZlLpUQO?si=e97c57e97111441e','chicken-fried.jpg'),
    ('Good Beer','Seaforth, Jordan Davis','ISFJ','happy','Good Beer','https://www.youtube.com/watch?v=JzGef7-WvTw','https://open.spotify.com/track/55M9eKCXJFCpid6WBVyEct?si=e3319c2b21c0480f','good-beer.jpg'),
    ('I Like The Sound Of That','Rascal Flatts','ISFJ','stressed','Rewind','https://www.youtube.com/watch?v=TIwKZLcQM0E','https://open.spotify.com/track/5S5rw0WLVCAux5B5bWCehK?si=fc249ee476d349f5','i-like-the-sound-of-that.jpg'),
    ('A Guy with a Girl','Blake Shelton','ISFJ','happy','If I''m Honest','https://www.youtube.com/watch?v=dnDYhIQ-YOI','https://open.spotify.com/track/5sjIhQzNljMVrDklI91ezp?si=daaa57ed07914fc3','a-guy-and-a-girl.jpg'),
    ('Whiskey Glasses','Morgan Wallen','ISFJ','stressed','If I Know Me','https://www.youtube.com/watch?v=FjBp30kjzTc','https://open.spotify.com/track/6foY66mWZN0pSRjZ408c00?si=d90963b5f2cf4bf4','whiskey-glasses.jpg'),
    ('Wagon Wheel','Darius Rucker','ISFJ','neutral','True Believers','https://www.youtube.com/watch?v=hvKyBcCDOB4','https://open.spotify.com/track/3xdjjKMcMOFgo1eQrfbogM?si=7835f2b0767b4139','wagon-wheel.jpg'),
    ('Good Girl','Dustin Lynch','ISFJ','neutral','Good Girl','https://www.youtube.com/watch?v=cPLctS4kqk8','https://open.spotify.com/track/5HnXcJJbNXQQ7tRlQ9VN1v?si=186fa8fc3d4f4c92','good-girl.jpg'),
    ('Beer Can''t Fix','Thomas Rhett, Jon Pardi','ISFJ','stressed','Center Point Road','https://www.youtube.com/watch?v=rct9Zs_Yd-I','https://open.spotify.com/track/7idmHTAQQPUFqdjXkoooXD?si=1488b1280bc34dc5','beer-cant-fix.jpg'),
    ('Drinkin'' Beer. Talkin'' God. Amen.','Chase Rice, Florida Georgia Line','ISFJ','happy','Drinkin''Beer.Talkin''God.Amen.','https://www.youtube.com/watch?v=wpS2oX9ASLc','https://open.spotify.com/track/1UYfAU2bwgjaM5rIIPQleC?si=a9d6dfa824354d3f','drinkin-beer-talking-god-amen.jpg'),
    ('Beers And Sunshine','Darius Rucker','ISFJ','happy','Beers And Sunshine','https://www.youtube.com/watch?v=s-vjdUg2bNk','https://open.spotify.com/track/36ISlLb12gKuCCVTYXC0gb?si=2cd5ccc760074f4a','beers-and-sunshine.jpg'),
    ('Tennessee Whiskey','Chris Stapleton','ISFJ','stressed','Traveller','https://www.youtube.com/watch?v=4zAThXFOy2c','https://open.spotify.com/track/3fqwjXwUGN6vbzIwvyFMhx?si=f80aae66363d4946','tennessee-whiskey.jpg'),
    ('She''s Country','Jason Aldean','ISFJ','neutral','Wider Open','https://www.youtube.com/watch?v=ZsvR6XAl1os','https://open.spotify.com/track/0PspNrE4MSjr1JeB4OW0jn?si=abf3557380b648aa','shes-country.jpg'),
    ('Knockin'' Boots','Luke Bryan','ISFJ','neutral','Born Here Live Here Die Here','https://www.youtube.com/watch?v=Ioz93bSi2uc','https://open.spotify.com/track/2opQESZb7JsRKCvWMBPeuv?si=09a29b7aff464b0e','knockin-boots.jpg'),
    ('Purple Lamborghini','Skrillex, Rick Ross','INTJ','angry','Purple Lamborghini','https://www.youtube.com/watch?v=ZkqyIoYAXV8','https://open.spotify.com/track/6JyuJFedEvPmdWQW0PkbGJ?si=adbe1a00804f4875','purple-lamborghini.jpg'),
    ('Where Are U Now','Jack U, Skrillex, Diplo, Justin Bieber','INTJ','stressed','Skrillex and Diplo present Jack U','https://www.youtube.com/watch?v=nntGTK2Fhb0','https://open.spotify.com/track/66hayvUbTotekKU3H4ta1f?si=9346b3c5f6ae499d','where-are-you-now.jpg'),
    ('Daylight','Joji, Diplo','INTJ','stressed','Daylight','https://www.youtube.com/watch?v=jOTqYGNaD6E','https://open.spotify.com/track/6Ed1q0X8oSKSm4IIhiQbYg?si=50932ad96bcc4c7b','daylight.jpg'),
    ('Harder, Better, Faster, Stronger','Daft Punk','INTJ','neutral','Discovery','https://www.youtube.com/watch?v=gAjR4_CbPpQ','https://open.spotify.com/track/5W3cjX2J3tjhG8zb6u0qHn?si=9e91401d28314c68','harder-better-faster-stronger.jpg'),
    ('Get Lucky','Daft Punk, Pharrell Williams, Nile Rodgers','INTJ','happy','Random Acess Memories','https://www.youtube.com/watch?v=5NV6Rdv1a3I','https://open.spotify.com/track/69kOkLUCkxIZYexIgSG8rq?si=77e378230d9f458e','get-lucky.jpg'),
    ('Wake Me Up','Avicii','INTJ','stressed','True','https://www.youtube.com/watch?v=IcrbM1l_BoI','https://open.spotify.com/track/0nrRP2bk19rLc0orkWPQk2?si=5b10e86c98a24d0f','wake-me-up.jpg'),
    ('Waiting For Love','Avicii','INTJ','stressed','Stories','https://www.youtube.com/watch?v=cHHLHGNpCSA','https://open.spotify.com/track/2P4OICZRVAQcYAV2JReRfj?si=64b1228528f8405d','waiting-for-love.jpg'),
    ('The Middle','Zedd, Maren Morris, grey','INTJ','stressed','The Middle','https://www.youtube.com/watch?v=Lj6Y6JCu-l4','https://open.spotify.com/track/09IStsImFySgyp0pIQdqAc?si=33c921f059314a8f','the-middle.jpg'),
    ('Stay','Zedd, Alessia Cara','INTJ','stressed','Stay','https://www.youtube.com/watch?v=h--P8HzYZ74','https://open.spotify.com/track/6uBhi9gBXWjanegOb2Phh0?si=e418a57fe6d6411d','stay.jpg'),
    ('Happier','Marshmello, Bastille','INTJ','stressed','Happier','https://www.youtube.com/watch?v=m7Bc3pLyij0','https://open.spotify.com/track/2dpaYNEQHiRxtZbfNsse99?si=2e7d09f91bda4757','happier.jpg'),
    ('Memories','David Guetta, Kid Cudi','INTJ','happy','Memories','https://www.youtube.com/watch?v=NUVCQXMUVnI','https://open.spotify.com/track/7KPr0YxECy4Q1k2F17Sa0Q?si=74f750d988014787','memories.jpg'),
    ('The Business','Tiesto','INTJ','stressed','The Business','https://www.youtube.com/watch?v=nCg3ufihKyU','https://open.spotify.com/track/6f3Slt0GbA2bPZlz0aIFXN?si=169f8845359547d2','the-business.jpg'),
    ('Feel So Close','Calvin Harris','INTJ','stressed','18 Months','https://www.youtube.com/watch?v=dGghkjpNCQ8','https://open.spotify.com/track/1gihuPhrLraKYrJMAEONyc?si=da78b4a0f5e843a0','feel-so-close.jpg'),
    ('Good Feeling','Flo Rida','INTJ','happy','Wild Ones','https://www.youtube.com/watch?v=3OnnDqH6Wj8','https://open.spotify.com/track/2LEF1A8DOZ9wRYikWgVlZ8?si=67f4252d89ec4563','good-feeling.jpg'),
    ('Safe And Sound','Capital Cities','INTJ','happy','In A Tidal Wave Of mystery','https://www.youtube.com/watch?v=47dtFZ8CFo8','https://open.spotify.com/track/6Z8R6UsFuGXGtiIxiD8ISb?si=fe751870211e4c73','safe-and-sound.jpg'),
    ('Levels','Avicii','INTJ','happy','True','https://www.youtube.com/watch?v=_ovdm2yX4MA','https://open.spotify.com/track/5B03nSG8pLE48jh7kmasuL?si=c81432de027c4c76','levels.jpg'),
    ('You and Me Flume Remix','Disclosure, Eliza Doolittle, Flume','INTJ','happy','Settle','https://www.youtube.com/watch?v=OUkkaqSNduU','https://open.spotify.com/track/3W2ZcrRsInZbjWylOi6KhZ?si=a6de998b79584be1','you-and-me-flume-remix.jpg'),
    ('Passionfruit','Drake','ESTP','stressed','More Life','https://www.youtube.com/watch?v=COz9lDCFHjw','https://open.spotify.com/track/5mCPDVBb16L4XQwDdbRUpz?si=4b76b2aea9dd4126','passionfruit.jpg'),
    ('Headlines','Drake','ESTP','stressed','Take Care','https://www.youtube.com/watch?v=Sn3SUnL44w4','https://open.spotify.com/track/6LxSe8YmdPxy095Ux6znaQ?si=13f57c5df3e44011','headlines.jpg'),
    ('Father Stretch My Hands Pt1','Kanye West','ESTP','neutral','The Life Of Pablo','https://www.youtube.com/watch?v=wuO4_P_8p-Q','https://open.spotify.com/track/4KW1lqgSr8TKrvBII0Brf8?si=7be439a48d6044ec','father-stretch-my-hand-pt1.jpg'),
    ('Ms.Jackson','Outkast','ESTP','happy','Stankonia','https://www.youtube.com/watch?v=CSD2J8yaMmM','https://open.spotify.com/track/0I3q5fE6wg7LIfHGngUTnV?si=51cf81dd3d8a432a','ms-jackson.jpg'),
    ('Can''t Tell Me Nothing','Kanye West','ESTP','angry','Graduation','https://www.youtube.com/watch?v=Vcljvd4Ef_o','https://open.spotify.com/track/0mEdbdeRFQwBhN4xfyIeUM?si=ba0d0c586f9d4b85','cant-tell-me-nothing.jpg'),
    ('Money Trees','Kendrick Lamar','ESTP','stressed','good kid, m.A.A.d city','https://www.youtube.com/watch?v=HJNa9Ih3haA','https://open.spotify.com/track/2HbKqm4o0w5wEeEFXm2sD4?si=502ffd0ac76e45e8','money-trees.jpg'),
    ('4:44','Jay Z','ESTP','stressed','4:44','https://www.youtube.com/watch?v=UMqr0NjQprE','https://open.spotify.com/track/1gT5TGwbkkkUliNzHRIGi1?si=6e5ea7d630a94020','444.jpg'),
    ('Best I Ever Had','Drake','ESTP','stressed','So Far Gone','https://www.youtube.com/watch?v=Zfp3KfYH0xA','https://open.spotify.com/track/3QLjDkgLh9AOEHlhQtDuhs?si=cf48932b39dd4be5','best-i-ever-had.jpg'),
    ('Bound 2','Kanye West','ESTP','neutral','Yeezus','https://www.youtube.com/watch?v=BBAtAM7vtgc','https://open.spotify.com/track/3sNVsP50132BTNlImLx70i?si=e67505656cea4f24','bound-2.jpg'),
    ('No Role Modelz','J Cole','ESTP','stressed','2014 Forest Hills Drive','https://www.youtube.com/watch?v=8HBcV0MtAQg','https://open.spotify.com/track/68Dni7IE4VyPkTOH9mRWHr?si=f39b78d2112544bd','no-role-modelz.jpg'),
    ('Heartless','Kanye West','ESTP','stressed','808s and Heartbreak','https://www.youtube.com/watch?v=Co0tTeuUVhU','https://open.spotify.com/track/4EWCNWgDS8707fNSZ1oaA5?si=3bf22a928f07446a','heartless.jpg'),
    ('Pursuit Of Happiness','Kid Cudi','ESTP','stressed','Man On The Moon: The End Of Day','https://www.youtube.com/watch?v=7xzU9Qqdqww','https://open.spotify.com/track/6MtKObWYda2qnNIpJI21uD?si=374b81bd62a2497b','pursuit-of-happiness.jpg'),
    ('The Heart Part 5','Kendrick Lamar','ESTP','angry','The Heart Part 5','https://www.youtube.com/watch?v=uAPUkgeiFVY','https://open.spotify.com/track/5MMW4CZsZiZt2iuqAXzzWC?si=9bc349b1446844b9','the-heart-part-5.jpg'),
    ('3005','Childish Gambino','ESTP','happy','Because the Internet','https://www.youtube.com/watch?v=EIRguVEYPeQ','https://open.spotify.com/track/2ZltjIqztEpZtafc8w0I9t?si=b4e1766bd670441e','3005.jpg'),
    ('Feels','Calvin Harris, Pharrell Williams, Katy Perry, Big Sean, Funk Wav','ESFP','happy','Funk Wav Bounces Vol.1','https://www.youtube.com/watch?v=ozv4q2ov3Mk','https://open.spotify.com/track/5bcTCxgc7xVfSaMV3RuVke?si=0c77b16bc65c4b33','feels.jpg'),
    ('Levitating','Dua Lipa, DaBaby','ESFP','happy','Future Nostalgia','https://www.youtube.com/watch?v=N000qglmmY0','https://open.spotify.com/track/5nujrmhLynf4yMoMtj8AQF?si=d0fe5b5996c6459d','levitating.jpg'),
    ('Don''t Start Now','Dua Lipa','ESFP','happy','Future Nostalgia','https://www.youtube.com/watch?v=oygrmJFKYZY','https://open.spotify.com/track/3PfIrDoz19wz7qK7tYeu62?si=f68e7df4559d4405','dont-start-now.jpg'),
    ('New Rules','Dua LIpa','ESFP','happy','Dua Lipa','https://www.youtube.com/watch?v=AyWsHs5QdiY','https://open.spotify.com/track/2xJCMIJfcNYDc5iR0sAm2O?si=69c17efec1b34b26','new-rules.jpg'),
    ('INDUSTRYBABY','Lil Nas X, Jack Harlow','ESFP','happy','MONTERO','https://www.youtube.com/watch?v=UTHLKHL_whs','https://open.spotify.com/track/5Z9KJZvQzH6PFmb8SNkxuk?si=ce03edb1b6be41c1','industry-baby.jpg'),
    ('Just A Cloud Away','Pharrell Williams','ESFP','happy','Just A Cloud Away','https://www.youtube.com/watch?v=reYRmpiVSyA','https://open.spotify.com/track/0DGTcMqvVR7fmBXgiG6jz4?si=ad55eb37b7394e53','just-a-cloud-away.jpg'),
    ('Kiss Me More','Doja Cat, SZA','ESFP','happy','Planet Her','https://www.youtube.com/watch?v=BhMC23ll2Rk','https://open.spotify.com/track/3DarAbFujv6eYNliUTyqtz?si=c7b51800eddf4661','kiss-me-more.jpg'),
    ('Woman','Doja Cat','ESFP','happy','Planet Her','https://www.youtube.com/watch?v=2V_uAAAH-_Q','https://open.spotify.com/track/6Uj1ctrBOjOas8xZXGqKk4?si=e94f931ccf7e412e','woman.jpg'),
    ('Good 4 u','Olivia Rodrigo','ESFP','angry','SOUR','https://www.youtube.com/watch?v=Bc9ijogGmtU','https://open.spotify.com/track/4ZtFanR9U6ndgddUvNcjcG?si=bf0e616d9ebc4398','good-4-u.jpg'),
    ('Watermelon Sugar','Harry Styles','ESFP','neutral','Fine Line','https://www.youtube.com/watch?v=7-x3uD5z1bQ','https://open.spotify.com/track/6UelLqGlWMcVH1E5c4H7lY?si=d92f6c289a054acf','watermelon-sugar.jpg'),
    ('Peaches','Justin Bieber, Daniel Caesar, Giveon','ESFP','stressed','Justice','https://www.youtube.com/watch?v=5rnawnfK2sQ','https://open.spotify.com/track/4iJyoBOLtHqaGxP12qzhQI?si=40ca2e78e2184603','peaches.jpg'),
    ('Say So','Doja Cat','ESFP','happy','Hot Pink','https://www.youtube.com/watch?v=uAYG46w1SCA','https://open.spotify.com/track/3Dv1eDb0MEgF93GpLXlucZ?si=cf62ba8be97b445e','say-so.jpg'),
    ('We''re Good','Dua Lipa','ESFP','happy','Future Nostalgia','https://www.youtube.com/watch?v=VwDTp0QTyY0','https://open.spotify.com/track/1diS6nkxMQc3wwC4G1j0bh?si=fd3e5230116a405a','were-good.jpg'),
    ('Sugar','Maroon 5','ESFP','neutral','V','https://www.youtube.com/watch?v=k8f4lcwKz6g','https://open.spotify.com/track/2iuZJX9X9P0GKaE93xcPjk?si=3f7230c7da5d4423','sugar.jpg'),
    ('hotgirlbummer','blackbear','ESFP','angry','hot girl bummer','https://www.youtube.com/watch?v=yMlKJGKyoCo','https://open.spotify.com/track/7aiClxsDWFRQ0Kzk5KI5ku?si=11720460af83447c','hot-girl-bummer.jpg'),
    ('Congratulations','Post Malone, Quavo','ESFP','stressed','Stoney','https://www.youtube.com/watch?v=FFhGqNa-Waw','https://open.spotify.com/track/3a1lNhkSLSkpJE4MSHpDu9?si=1211f5d84d794ae8','congratulations.jpg'),
    ('Heat Waves','Glass Animals','ESFP','stressed','Dreamland','https://www.youtube.com/watch?v=KT7F15T9VBI','https://open.spotify.com/track/3USxtqRwSYz57Ewm6wWRMp?si=39dba5ac306548f8','heat-waves.jpg'),
    ('Starboy','The Weeknd, Daft Punk','ESFP','stressed','Starboy','https://www.youtube.com/watch?v=3_g2un5M350','https://open.spotify.com/track/7MXVkk9YMctZqd1Srtv4MB?si=6b7f404d93a046af','starboy.jpg'),
    ('Get Lucky','Daft Punk, Pharrel Williams,, Nile Rodgers','ESFP','stressed','Get Lucky','https://www.youtube.com/watch?v=5NV6Rdv1a3I','https://open.spotify.com/track/2Foc5Q5nqNiosCNqttzHof?si=8b5b6682ffc74302','get-lucky.jpg'),
    ('Back In Black','AC/DC','ESTJ','angry','Back in Black','https://www.youtube.com/watch?v=pAgnJDJN4VA','https://open.spotify.com/track/08mG3Y1vljYA6bvDt4Wqkj?si=57b8d7e1f39b485e','back-in-black.jpg'),
    ('Thunderstruck','AC/DC','ESTJ','angry','The Razors Edge','https://www.youtube.com/watch?v=v2AC41dglnM','https://open.spotify.com/track/57bgtoPSgt236HzfBOd8kj?si=0b74177a95d24a58','thunderstruck.jpg'),
    ('T.N.T','AC/DC','ESTJ','angry','High Voltage','https://www.youtube.com/watch?v=NhsK5WExrnE','https://open.spotify.com/track/7LRMbd3LEoV5wZJvXT1Lwb?si=f21c846bf87c44a4','tnt.jpg'),
    ('Highway to Hell','AC/DC','ESTJ','angry','Highway to Hell','https://www.youtube.com/watch?v=l482T0yNkeo','https://open.spotify.com/track/2zYzyRzz6pRmhPzyfMEC8s?si=65e867409bad478c','highway-to-hell.jpg'),
    ('Sweet Child O'' Mine','Guns N'' Roses','ESTJ','neutral','Appetite For Destruction','https://www.youtube.com/watch?v=1w7OgIMMRc4','https://open.spotify.com/track/7snQQk1zcKl8gZ92AnueZW?si=12605b7f3524492b','sweet-child-of-mine.jpg'),
    ('Welcome To The Jungle','Guns N'' Roses','ESTJ','angry','Appetite For Destruction','https://www.youtube.com/watch?v=o1tj2zJ2Wvg','https://open.spotify.com/track/0G21yYKMZoHa30cYVi1iA8?si=4b8dc461515245e9','welcome-to-the-jungle.jpg'),
    ('Walk This Way','Aerosmith','ESTJ','neutral','Toys In The Attic','https://www.youtube.com/watch?v=4c8O2n1Gfto','https://open.spotify.com/track/5SZ6zX4rOrEQferfFC2MfP?si=5e155dd154f54b4a','walk-this-way.jpg'),
    ('Rock And Roll All Nite','KISS','ESTJ','happy','Dressed To Kill','https://www.youtube.com/watch?v=f-S3X2saSwM','https://open.spotify.com/track/6KTv0Z8BmVqM7DPxbGzpVC?si=ffba54a25fae47f3','rock-and-roll.jpg'),
    ('Crazy Train','Ozzy Osbourne','ESTJ','angry','Blizzard Of Ozz','https://www.youtube.com/watch?v=FVovq9TGBw0','https://open.spotify.com/track/7ACxUo21jtTHzy7ZEV56vU?si=9f3e9e516e9247ac','crazy-train.jpg'),
    ('Smells Like Teen Spirit','Nirvana','ESTJ','stressed','Nevermind','https://www.youtube.com/watch?v=hTWKbfoikeg','https://open.spotify.com/track/5ghIJDpPoe3CfHMGu71E6T?si=c6b3296488254d25','smells-like-teen-spirit.jpg'),
    ('Another One Bites The Dust','Queen','ESTJ','neutral','The Game','https://www.youtube.com/watch?v=PqUenEMwsdQ','https://open.spotify.com/track/57JVGBtBLCfHw2muk5416J?si=5d3fb41e4a1f4c6a','another-one-bites-the-dust.jpg'),
    ('Livin'' On A Prayer','Bon Jovi','ESTJ','stressed','Slippery When Wet','https://www.youtube.com/watch?v=lDK9QqIzhwk','https://open.spotify.com/track/0J6mQxEZnlRt9ymzFntA6z?si=f65d3768109d4911','livin-on-a-prayer.jpg'),
    ('Kickstart My Heart','Motley Crue','ESTJ','angry','Dr.Feelgood','https://www.youtube.com/watch?v=mVurA44hwiw','https://open.spotify.com/track/7GonnnalI2s19OCQO1J7Tf?si=7207cb246fdb4ea4','kickstart-my-heart.jpg'),
    ('I Was Made For Lovin'' You','KISS','ESTJ','stressed','Dynasty','https://www.youtube.com/watch?v=ZhIsAZO5gl0','https://open.spotify.com/track/07q0QVgO56EorrSGHC48y3?si=2882e19244d34497','i-was-made-for-loving.jpg'),
    ('Barracuda','Heart','ESTJ','angry','Little Queen','https://www.youtube.com/watch?v=VdOkQ6THDVw','https://open.spotify.com/track/4KfSdst7rW39C0sfhArdrz?si=8d9ee78679774c0e','barracuda.jpg'),
    ('The Barber of Seville','Gioachino Rossini','ISTJ','neutral','Rossini - Ouvertures','https://www.youtube.com/watch?v=OloXRhesab0','https://open.spotify.com/track/3PGPfeQTaZgHnmofWYBHSW?si=9ceb3c271b074224','the-barber-of-seville.jpg'),
    ('Nocturne in B flat minor','Frederic Chopin','ISTJ','stressed','Chopin: Nocturnes','https://www.youtube.com/watch?v=t-JD2bnNQvY','https://open.spotify.com/track/2KvwdV2iYrOuSyNJ31P5bH?autoplay=true','nocturne.jpg'),
    ('Nocturne in E Flat Major','Frederic Chopin','ISTJ','stressed','Chopin: Nocturnes','https://www.youtube.com/watch?v=9E6b3swbnWg','https://open.spotify.com/track/1VNvsvEsUpuUCbHpVop1vo?si=6c61e3d9175a4734','nocturne.jpg'),
    ('Waltz in A minor','Frederic Chopin','ISTJ','stressed','Chopin: Waltzes, etc.','https://www.youtube.com/watch?v=algM0c_u99k','https://open.spotify.com/track/0aJDvIeUkceMRueD84rRDR','waltz-aminor.jpg'),
    ('Piano Concerto No.21','Wolfgang Mozart','ISTJ','stressed','Mozart: Piano Concertos, Vol. 6','https://www.youtube.com/watch?v=df-eLzao63I','https://open.spotify.com/track/01QJ0UbSTP9Y49R4Q9qiFs','piano-concerto-21.jpg'),
    ('The Well Tempered Clavier','J.S.Bach','ISTJ','stressed','The Well Tempered Clavier Book 1','https://www.youtube.com/watch?v=ezZdbzreNcs','https://open.spotify.com/track/2XxC430QMotGdympDP1aBo?si=9193d8c997364d76','prelude-and-fugue-1.jpg'),
    ('Arabesque No.1','Debussy','ISTJ','stressed','Debussy, C.:Piano Music (Complete), Vol. 3-Suite Bergamasque/Children''s Corner','https://www.youtube.com/watch?v=Yh36PaE-Pf0','https://open.spotify.com/track/1btSclzWM6mSKy0pFACPCZ?si=5c3fa9f7e4ee4b07','arabesque.jpg'),
    ('Fracture','Stephan Moccio','ISTJ','stressed','Fracture','https://www.youtube.com/watch?v=hYH80WGPet8','https://open.spotify.com/track/2m2GJpBjQNNphaCgBeoj7R?si=d98f82149cc0402e','fracture.jpg'),
    ('Clair de Lune','Claude Debrussy','ISTJ','stressed','Debussy, Clair De Lune and Other Piano Favourites','https://www.youtube.com/watch?v=CvFH_6DNRCY','https://open.spotify.com/track/5u5aVJKjSMJr4zesMPz7bL?si=49ef37c460b74804','clair-de-lune.jpg'),
    ('2 Melodies','Anton Rubinstein','ISTJ','happy','Romantic Piano favourites, Vol 1.','https://www.youtube.com/watch?v=N2UJXn0fNi4','https://open.spotify.com/track/292v462HzpqvKNha41SiWZ','melodies-2.jpg'),
    ('String Quartet in F Minor','Joseph Haydn','ISTJ','angry','The Haydn Project','https://www.youtube.com/watch?v=s9olhyCmosw','https://open.spotify.com/track/3F1KgQJoI75WV9DSDJmKv0','string-quartet-fminor.jpg'),
    ('Cello Suite No. 1 in G Major','J.S.Bach','ISTJ','happy','Bach: Cello Suites Nos. 1,5 and 6','https://www.youtube.com/watch?v=1prweT95Mo0','https://open.spotify.com/track/17i5jLpzndlQhbS4SrTd0B?si=7b6b3567558648bd','cello-suite.jpg'),
    ('No. 24 in A Minor','Niccolo Paganini','ISTJ','angry','Paganini: 24 Caprices','https://www.youtube.com/watch?v=r0m21rGZXx8','https://open.spotify.com/track/6cC6h5E351deEGFd7Kh9uy','paganini-24-caprices.jpg'),
    ('Smokin Out The Window','Silk Sonic','ESFJ','angry','An Evening with Silk Sonic','https://www.youtube.com/watch?v=GG7fLOmlhYg','https://open.spotify.com/track/3xVZYkcuWalGudeKl861wb?si=1d2a5bf090484314','smokin-out-the-window.jpg'),
    ('Wildest Dreams','Taylor Swift','ESFJ','stressed','Wildest Dreams (Taylor''s Version)','https://www.youtube.com/watch?v=IdneKLhsWOQ','https://open.spotify.com/track/1Ov37jtRQ2YNAe8HzfczkL?si=17bfebaab1c64951','wildest-dreas.jpg'),
    ('Wait a Minute!','WILLOW','ESFJ','stressed','ARDIPITHECUS','https://www.youtube.com/watch?v=1Xfdjqa5dfY','https://open.spotify.com/track/0y60itmpH0aPKsFiGxmtnh?si=8b30f06fb5344e6e','wait-a-minute.jpg'),
    ('good 4 u','Olivia Rodrigo','ESFJ','angry',NULL,'https://www.youtube.com/watch?v=gNi_6U5Pm_o','https://open.spotify.com/track/4ZtFanR9U6ndgddUvNcjcG?si=decd63086d154a55','good-4-u.jpg'),
    ('3 Nights','Dominic FIke','ESFJ','relaxed','Don''t Forget About Me, Demos','https://www.youtube.com/watch?v=OWKzRngush4','https://open.spotify.com/track/0uI7yAKUf52Cn7y3sYyjiX?si=d2f6da4d29cc462f','3-nights.jpg'),
    ('Sunflower','Post Malone, Swae Lee','ESFJ','relaxed','Sunflower','https://www.youtube.com/watch?v=ApXoWvfEYVU','https://open.spotify.com/track/1A6OTy97kk0mMdm78rHsm8?si=771423db17bf401b','sunflower.jpg'),
    ('Kiss Me More','Doja Cat, SZA','ESFJ','happy','Plant Her','https://www.youtube.com/watch?v=0EVVKs6DQLo','https://open.spotify.com/track/3DarAbFujv6eYNliUTyqtz?si=48a3ebdd7ac44bef','kiss-me-more.jpg'),
    ('Butter','BTS','ESFJ','happy','Butter','https://www.youtube.com/watch?v=WMweEpGlu_U','https://open.spotify.com/track/2bgTY4UwhfBYhGT4HUYStN?si=a4715c230e364da5','butter.jpg'),
    ('Leave The Door Open','Silk Sonic','ESFJ','happy','An Evening with Silk Sonic','https://www.youtube.com/watch?v=adLGHcj_fmA','https://open.spotify.com/track/7MAibcTli4IisCtbHKrGMh?si=262a37a081504171','leave-the-door-open.jpg'),
    ('High Hopes','Panic! At the Disco','ESFJ','neutral','Pray for the Wicked','https://www.youtube.com/watch?v=IPXIgEAGe4U','https://open.spotify.com/track/1rqqCSm0Qe4I9rUvWncaom?si=b943fc798a0f43f2','high-hopes.jpg'),
    ('THATS WHAT I WANT','Lil Nas X','ESFJ','happy','MONTERO','https://www.youtube.com/watch?v=QDYDRA5JPLE','https://open.spotify.com/track/0e8nrvls4Qqv5Rfa2UhqmO?si=25de947f63eb466a','thats-what-i-want.jpg'),
    ('Whats Poppin','Jack Harlow','ESFJ','neutral','Thats What They All Say','https://www.youtube.com/watch?v=HIwAI05Y1fU','https://open.spotify.com/track/0ZLuW8uOXdFNWcI40C0OC2?si=f89100e524dc401d','whats-poppin.jpg'),
    ('Need to Know','Doja Cat','ESFJ','neutral','Planet Her','https://www.youtube.com/watch?v=dI3xkL7qUAc','https://open.spotify.com/track/3Vi5XqYrmQgOYBajMWSvCi?si=d639e044fee7407d','need-to-know.jpg'),
    ('edamame','bbno$, Rich Brian','ESFJ','neutral','edamame','https://www.youtube.com/watch?v=K6BRna4_bmg','https://open.spotify.com/track/1uMHCAyGmHqyygoNRuo7MV?si=d29d80069acf4efa','edamame.jpg'),
    ('Laugh Now Cry Later','Drake, Lil Durk','ESFJ','neutral','Laugh Now Cry Later','https://www.youtube.com/watch?v=JFm7YDVlqnI','https://open.spotify.com/track/2SAqBLGA283SUiwJ3xOUVI?si=72f71f7b711f427f','laugh-now-cry-later.jpg'),
    ('Feel It Still','Portugal. The Man','ESFJ','happy','Woodstock','https://www.youtube.com/watch?v=pBkHHoOIIn8','https://open.spotify.com/track/6QgjcU0zLnzq5OrUoSZ3OK?si=cb304b7030eb45c9','feel-it-still.jpg'),
    ('One Dance','Drake, WizKid, Kyla','ESFJ','neutral','Views','https://www.youtube.com/watch?v=iAbnEUA0wpA','https://open.spotify.com/track/1zi7xx7UVEFkmKfv06H8x0?si=a3b3e20452ca48e4','one-dance.jpg'),
    ('God''s Plan','Drake','ESFJ','happy','Scorpion','https://www.youtube.com/watch?v=xpVfcZ0ZcFM','https://open.spotify.com/track/6DCZcSspjsKoFjzjrWoCdn?si=c14b85989288449c','gods-plan.jpg'),
    ('As It Was','Harry Styles','ESFJ','stressed','As It Was','https://www.youtube.com/watch?v=H5v3kku4y6Q','https://open.spotify.com/track/4LRPiXqCikLlN15c3yImP7?si=2e62e91f96de4f8b','as-it-was.jpg'),
    ('STAY','The Kid Laroi, Justin Bieber','ESFJ','stressed','F*CK LOVE 3: OVER YOU','https://www.youtube.com/watch?v=kTJczUoc26U','https://open.spotify.com/track/5PjdY0CKGZdEuoNab3yDmX?si=8e96729f85d74b11','stay-laroi.jpg'),
    ('Xtal','Aphex Twins','INFJ','relaxed','Selected Ambient Works 85-92','https://www.youtube.com/watch?v=2tOutF8B3f8','https://open.spotify.com/track/7o2AeQZzfCERsRmOM86EcB?si=d99e5b21fa8e4809','xtal.jpg'),
    ('Roygbiv','Boards of Canada','INFJ','relaxed','Music Has The Right To Children','https://www.youtube.com/watch?v=0nnqGDZnWhU','https://open.spotify.com/track/2XQSgmtEY2titXhfY414dy?si=177db50c0fd94543','roygbiv.jpg'),
    ('14:31','Global Communication','INFJ','relaxed','76:14','https://www.youtube.com/watch?v=PW5T8SMEOjk','https://open.spotify.com/track/3gpLIMd0ySkcorvVIMtmTp?si=da69f6dadc0a49b7','1431.jpg'),
    ('5 23','Global Communication','INFJ','relaxed','76:14','https://www.youtube.com/watch?v=q-O0r-jLtx4','https://open.spotify.com/track/7rGEbcLvRsoehrdQ2LC50G?si=debd1aa5686f44f5','523.jpg'),
    ('The Box - Part 2','Orbital','INFJ','relaxed','In Sides','https://www.youtube.com/watch?v=vGvFObnwKNc','https://open.spotify.com/track/1kV6GsEtVGmPehcGpmYtnr?si=c5b70d59f7f14c38','the-box-pt1.jpg'),
    ('The Box - Pt. 1','Orbital','INFJ','relaxed','In Sides','https://www.youtube.com/watch?v=x6hdkwR-rSw','https://open.spotify.com/track/5TbwZ0OSuU1fGtQ8aTgiZP?si=a5351113c3414853','the-box-pt2.jpg'),
    ('Slip','Autechre','INFJ','relaxed','Amber','https://www.youtube.com/watch?v=HB2NJ8deZ64','https://open.spotify.com/track/6wTXs58QJBjjwWVwX4ECTM?si=4033367ba7824c8c','slip.jpg'),
    ('Montreal','Autechre','INFJ','relaxed','Amber','https://www.youtube.com/watch?v=h_segRH6LKA','https://open.spotify.com/track/4G5lTzfkklIotjt28dhlz3?si=b8f1c38243cb4b1f','montreal.jpg'),
    ('Konigsforst 1','GAS','INFJ','relaxed','Konigsforst','https://www.youtube.com/watch?v=pJMq1bZdEq4','https://open.spotify.com/track/7joLh1gqRVsHuwccyjILbj?si=ed0a63b7283b4655','konigsforst'),
    ('ゆめうつつ','Lamp','ENFP','relaxed','ランプ幻想','https://www.youtube.com/watch?v=AJdTBPuZkHU','https://open.spotify.com/track/1GTC0DN9LGOdP0NdvoHyX7?si=862a55f54e704914','lamp-1.jpg'),
    ('For Lovers','Lamp','ENFP','relaxed','恋人へ','https://www.youtube.com/watch?v=-ILcH66zGcY','https://open.spotify.com/track/6BGNjTZ8zp9MlsIydBa7A9?si=ed0ef4e66a574da4','lamp-2.jpg'),
    ('いきのこり●ぼくら','Ichiko Aoba','ENFP','relaxed','0','https://www.youtube.com/watch?v=byvta9LHo2o','https://open.spotify.com/track/6ad7bQ48TlqAgebCExUJVe?si=68217948f9ff4497','0.jpg'),
    ('One Summer Day','Joe Hisaishi','ENFP','relaxed','Spirited Away Soudtrack','https://www.youtube.com/watch?v=TK1Ij_-mank','https://open.spotify.com/track/3gFQOMoUwlR6aUZj81gCzu?si=eaf7f39c38d64a19','one-summers-day.jpg'),
    ('Merry-Go-Round of Life','Joe Hisaishi','ENFP','relaxed','Howl''s Moving Castle Soundtrack','https://www.youtube.com/watch?v=f7SS57LFPco','https://open.spotify.com/track/6IZF8hi9J6EtFDLQqOlSbu?si=e593905f991c4816','merry-go-round-of-life.jpg'),
    ('(forever?????????)','glass beach','ENFP','relaxed','the first glass beach album','https://www.youtube.com/watch?v=PcZdQbgSQvs','https://open.spotify.com/track/0wNOZ8FmGnnNH1YGEWjzLK?si=13559995fee74434','forever.jpg'),
    ('recently,','Liana Flores','ENFP','relaxed','recently','https://www.youtube.com/watch?v=N8q0WpDIaiY','https://open.spotify.com/track/1djCoU5rvnq2zXFyD2iqq4?si=b6481241b25341c1','recently.jpg'),
    ('Okinawa','92914','ENFP','relaxed','Okinawa','https://www.youtube.com/watch?v=KzHOPckFmwc','https://open.spotify.com/track/1CfcKv1RLdJBWhRHAZgVdf?si=9162c542e79f4fa9','okinawa.jpg'),
    ('The Ocean Waves','Shigeru Nagata','ENFP','relaxed','The Ocean Waves','https://www.youtube.com/watch?v=tvML4G1jFMo','https://open.spotify.com/track/4OewEEF60LvBU2AZSyoeah?si=03fceb612a2f4ba3','the-ocean-waves.jpg'),
    ('The Sea','Kinokoteikoku','ENFP','relaxed','タイム・ラプス','https://www.youtube.com/watch?v=pRO4Eh_mGkg&list=PLcgDqEXHyDZ_mxspPH2IQhamdcNoWza8N','https://open.spotify.com/track/0BXTmQvqQC2cn0F3XuWWBH?si=ec9c7ada11aa450b','the-sea.jpg'),
    ('Kinmokuseino Yoru','Kinokoteikoku','ENFP','relaxed','渦になる','https://www.youtube.com/watch?v=VJ-GDz04rlw','https://open.spotify.com/track/27udJcfu06TvbbOpgfxIlw?si=03192beb8464488c','kinoko.jpg'),
    ('Karappo no Isu','Taeko Onuki','ENFP','relaxed','SUNSHOWER','https://www.youtube.com/watch?v=kwh-lz5lqhY','https://open.spotify.com/track/6FtGDFcQDKiU7UVoa0DK22?si=bbd05aec34f24682','karappo-no-isu.jpg'),
    ('悲しくてやりきれない','Kotringo','ENFP','relaxed','picnic album','https://www.youtube.com/watch?v=HF93aqG9rhI','https://open.spotify.com/track/5VO9PtiWH5KgldpYrQWwIx?si=6c2e52c4607d4919','kotringo.jpg'),
    ('Landscape With a Fairy','aspidistrafly','ENFP','relaxed','A Little Fable','https://www.youtube.com/watch?v=dYCW7i2OiKk','https://open.spotify.com/track/19doORzyzOFARW6I0Fydc8?si=e24a0d1672eb490a','landscape-with-a-fairy.jpg'),
    ('oyasumi','mamerico','ENFP','relaxed','minuscule','https://www.youtube.com/watch?v=8y-HE0_-qHM','https://open.spotify.com/track/40oxt995AdrZ7O4RtVWMIT?si=e0fa5ff1d9b247c3','oyasumi.jpg'),
    ('Any Song','ZICO','INFP','happy','Any song','https://www.youtube.com/watch?v=UuV2BmJ1p_I','https://open.spotify.com/track/1iIhGHzzrzqQfuNkFI2qAn?si=a340f6b31aa84b50','any-song.jpg'),
    ('Butter','BTS','INFP','happy','Butter','https://www.youtube.com/watch?v=WMweEpGlu_U','https://open.spotify.com/track/1mWdTewIgB3gtBM3TOSFhB?si=6a5b13a4fb004db8','butter.jpg'),
    ('Dynamite','BTS','INFP','happy','BE','https://www.youtube.com/watch?v=gdZLi9oWNZg','https://open.spotify.com/track/5QDLhrAOJJdNAmCTJ8xMyW?si=9686f62534dd4fd7','dynamite.jpg'),
    ('That That','PSY, SUGA','INFP','happy','PSY 9th','https://www.youtube.com/watch?v=8dJyRm2jJ-U','https://open.spotify.com/track/5oH4DQAuu1J1800RzUsBWa?si=44b9d9a062a642b5','that-that.jpg'),
    ('Kill This Love','BLACKPINK','INFP','happy','KILL THIS LOVE','https://www.youtube.com/watch?v=ioNng23DkIM','https://open.spotify.com/track/6hvczQ05jc1yGlp9zhb95V?si=a892a4fb63e24a11','kill-this-love.jpg'),
    ('Obsession','EXO','INFP','happy','OVSESSION','https://www.youtube.com/watch?v=uxmP4b2a0uY','https://open.spotify.com/track/7fK0csBoqbcgUuWGV0cpoD?si=be1a3385b5a141d7','obsession.jpg'),
    ('BOSS','NCT, NCT U','INFP','happy','NCT 2018 EMPATHY','https://www.youtube.com/watch?v=0AUFyFEt35g','https://open.spotify.com/track/0ErzcmZ2gIwX7X0xSMQPix?si=dfc6f297ae4e4568','boss.jpg'),
    ('Sour Candy','Lady Gaga, BLACKPINK','INFP','happy','Chromatica','https://www.youtube.com/watch?v=fnPn6At3v28','https://open.spotify.com/track/1IWNylpZ477gIVUDpJL66u?si=d65841d2b9cf46cf','sour-candy.jpg'),
    ('FANCY','TWICE','INFP','happy','FANCY YOU','https://www.youtube.com/watch?v=kOHB85vDuow','https://open.spotify.com/track/2qQpFbqqkLOGySgNK8wBXt?si=949c5ded69b54dfc','fancy.jpg'),
    ('Alcohol-Free','TWICE','INFP','happy','Taste of Love','https://www.youtube.com/watch?v=XA2YEHn-A8Q','https://open.spotify.com/track/0BTaaKT4RMbs5M73tOHX5Y?si=46c12a5d5e8a406f','alcohol-free.jpg'),
    ('TOMBOY','(G)I-IDLE','INFP','happy','I NEVER DIE','https://www.youtube.com/watch?v=Jh4QFaPmdss','https://open.spotify.com/track/0IGUXY4JbK18bu9oD4mPIm?si=96cf67d539aa4c52','tomboy.jpg'),
    ('MANIAC','Stray Kids','INFP','happy','ODDINARY','https://www.youtube.com/watch?v=OvioeS1ZZ7o','https://open.spotify.com/track/63irPUP3xB74fHdw1Aw9zR?si=5388dc644f444cc1','maniac.jpg'),
    ('THRILL RIDE','THE BOYS','INFP','happy','THE BOYZ  6TH MINI ALBUM','https://www.youtube.com/watch?v=XMs2CIiqRDI','https://open.spotify.com/track/3wEYYVD6uC3A3LhVhqARZv?si=ed3d49499d874806','thrill-ride.jpg'),
    ('MAVERICK','THE BOYS','INFP','happy','THE BOYZ 3rd Single Alubm','https://www.youtube.com/watch?v=sQTGAggO0Gw','https://open.spotify.com/track/1Ylu1Il2czce9eQQXtDXwO?si=8768a8bac18f4482','maverick.jpg'),
    ('BANG BANG BANG','BIGBANG','INFP','happy','MADE','https://www.youtube.com/watch?v=2ips2mM7Zqw','https://open.spotify.com/track/0QIRm9sUkGnezGznkWCqCo?si=4676bc2956404bb2','bang-bang-bang.jpg'),
    ('Power Up','Red Velvet','INFP','happy','Summer Magic','https://www.youtube.com/watch?v=aiHSVQy9xN8','https://open.spotify.com/track/381g0b6QZxC13SzA2HRMIc?si=203dcb0600074606','power-up.jpg'),
    ('CALL ME BABY','EXO','INFP','happy','EXODUS','https://www.youtube.com/watch?v=yWfsla_Uh80','https://open.spotify.com/track/6Rx0ORYPP3GH9rTvGS5Vy8?si=e3be254a25534316','call-me-baby.jpg'),
    ('LIT','ONEUS','INFP','happy','FLY WITH US','https://www.youtube.com/watch?v=ggPF6Wb8A50','https://open.spotify.com/track/5UX7u7znDeHnDa3iynEhcm?si=16f2bce04bb3400f','lit.jpg'),
    ('Just right','GOT7','INFP','happy','Just right','https://www.youtube.com/watch?v=vrdk3IGcau8','https://open.spotify.com/track/4ER58qECydWokIsgqtysWu?si=6c962fa1c5594fe1','just-right.jpg');